const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const rows=[1,2,3,4,5,6,7,8,9,10];
const learnCards=[
 {title:'Die 1er-Reihe',text:'Bei der 1er-Reihe bleibt die Zahl immer gleich.',example:'1 × 4 = 4 · 1 × 7 = 7 · 1 × 9 = 9',question:'1 × 8 = ?',answer:8},
 {title:'Die 2er-Reihe: Verdoppeln',text:'Mal 2 bedeutet: Verdopple die Zahl.',example:'6 × 2 = 6 + 6 = 12',dots:[2,6],question:'4 × 2 = ?',answer:8},
 {title:'Die 5er-Reihe',text:'Ergebnisse der 5er-Reihe enden immer auf 0 oder 5.',example:'5 · 10 · 15 · 20 · 25 · 30 · 35 · 40 · 45 · 50',question:'Welches Ergebnis gehört zur 5er-Reihe?',options:[23,35,42,58],answer:35},
 {title:'Die 10er-Reihe',text:'Bei ×10 hängst du einfach eine 0 an.',example:'3 × 10 = 30 · 7 × 10 = 70 · 9 × 10 = 90',question:'7 → ?',options:[17,70,77,700],answer:70},
 {title:'🔄 Tauschaufgaben',text:'Beim Multiplizieren darfst du die beiden Zahlen vertauschen. Das Ergebnis bleibt gleich.',example:'3 × 7 = 21   und   7 × 3 = 21',dots:[3,7],question:'Welche Tauschaufgabe gehört zu 4 × 8?',options:['8 × 4','4 + 8','8 + 4','4 × 4'],answer:'8 × 4'},
 {title:'➕ Nachbaraufgaben',text:'Kennst du eine Aufgabe, kannst du eine benachbarte Aufgabe durch Addieren ableiten.',example:'5 × 6 = 30  →  30 + 6 = 36  →  6 × 6 = 36',question:'Wenn 5 × 7 = 35 gilt: Wie viel ist 6 × 7?',answer:42},
 {title:'Von leicht zu schwierig',text:'Nutze sichere Reihen, um schwierigere Aufgaben zu zerlegen.',example:'6 × 7 = 5 × 7 + 1 × 7 = 35 + 7 = 42',question:'Nutze 5 × 8: 6 × 8 = ?',answer:48}
];
const state={view:'home',series:null,tasks:[],index:0,points:0,streak:0,hint:0,answered:false,challenge:false,duel:{player:0,computer:0},stats:JSON.parse(localStorage.getItem('linguacode-einmaleins-stats')||'{}')};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function task(a,b,type){return {a,b,result:a*b,row:a,other:b,type:type||['input','choice','missing','truefalse','swap'][Math.floor(Math.random()*5)]}}
function makeTasks(series,count=10){const list=[];for(let i=0;i<count;i++){let a=series==='all'?rows[Math.floor(Math.random()*10)]:Number(series);let b=rows[Math.floor(Math.random()*10)];if(Math.random()<.45)[a,b]=[b,a];list.push(task(a,b))}return list}
function save(){localStorage.setItem('linguacode-einmaleins-stats',JSON.stringify(state.stats));localStorage.setItem('linguacode-einmaleins-points',String(state.points))}
function updateStat(t,ok){const key=String(t.row);if(!state.stats[key])state.stats[key]={seen:0,correct:0};state.stats[key].seen++;if(ok)state.stats[key].correct++;save();renderMastery()}
function show(view){state.view=view;$$('.screen').forEach(s=>{const on=s.id===view;s.hidden=!on;s.classList.toggle('active',on)});$$('.path button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='home')renderMastery();if(view==='learn')renderLearn();if(view==='patterns')renderPatterns();if(view==='table')renderTable()}
function renderSeries(container,onClick){$(container).innerHTML=rows.map(n=>`<button class="series-button" data-series="${n}" type="button">${n}er</button>`).join('');$$(`${container} .series-button`).forEach(b=>b.addEventListener('click',()=>onClick(b.dataset.series,b)))}
function renderMastery(){const total=rows.reduce((sum,n)=>sum+(state.stats[n]?.seen||0),0);$('#home-points').textContent=localStorage.getItem('linguacode-einmaleins-points')||'0';$('#mastery-list').innerHTML=rows.map(n=>{const s=state.stats[n]||{seen:0,correct:0};const pct=s.seen?Math.round(s.correct/s.seen*100):0;const label=s.seen<3?'Noch üben':pct>=80?'Sicher': 'Üben';const icon=s.seen<3?'🔴':pct>=80?'✅':'🟡';return `<div class="mastery"><span>${n}er</span><div class="mastery-bar"><i style="width:${Math.min(pct,100)}%"></i></div><b title="${s.seen} Aufgaben">${icon} ${label}</b></div>`}).join('')}
function renderLearn(){const c=learnCards[state.index%learnCards.length];$('#learn-card').innerHTML=`<div><p class="kicker">KARTE ${state.index+1} VON ${learnCards.length}</p><h2>${c.title}</h2><p>${c.text}</p><div class="learn-example">${c.example}</div>${c.dots?dots(c.dots[0],c.dots[1]):''}<p><strong>${c.question}</strong></p><div class="learn-options">${c.options?c.options.map(o=>`<button class="option" type="button" data-answer="${o}">${o}</button>`).join(''):`<input class="answer-input" id="learn-answer" inputmode="numeric" aria-label="Antwort"><button class="primary" id="learn-check" type="button">Prüfen</button>`}</div><div id="learn-feedback" class="feedback" hidden></div></div>`;$$('#learn-card .option').forEach(b=>b.addEventListener('click',()=>checkLearn(b.dataset.answer,c.answer)));$('#learn-check')?.addEventListener('click',()=>checkLearn($('#learn-answer').value,c.answer));$('#learn-answer')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#learn-check').click()})}
function checkLearn(value,answer){const f=$('#learn-feedback');const ok=String(value).trim()===String(answer);f.hidden=false;f.className=`feedback ${ok?'good':'bad'}`;f.textContent=ok?'✅ Richtig! Weiter mit dem nächsten Trick.':`💡 Noch nicht: Denke an ${answer}.`}
function dots(rowsCount,cols){let html='<div class="dots" style="--cols:'+cols+'">';for(let i=0;i<rowsCount*cols;i++)html+='<i class="dot" aria-hidden="true"></i>';return html+'</div>'}
function renderPatterns(){const data=[['2er-Reihe','2 · 4 · 6 · 8 · 10 · 12','Alle Ergebnisse sind gerade.'],['5er-Reihe','5 · 10 · 15 · 20 · 25 · 30','Die Endziffern sind immer 0 oder 5.'],['10er-Reihe','10 · 20 · 30 · 40 · 50','An die Zahl kommt eine 0.']];$('#pattern-card').innerHTML=data.map(x=>`<article class="pattern-card panel"><p class="kicker">${x[0]}</p><h2>Was fällt dir auf?</h2><p class="pattern-sequence">${x[1]}</p><p>${x[2]}</p></article>`).join('')}
function startPractice(series){state.series=series;state.tasks=makeTasks(series);state.index=0;state.points=0;state.streak=0;state.hint=0;state.answered=false;$('#practice-picker').hidden=true;$('#task-area').hidden=false;$('#practice-title').textContent=series==='all'?'Gemischtes Training':`${series}er-Reihe`;renderTask()}
function renderTask(){const t=state.tasks[state.index];state.answered=false;state.hint=0;$('#task-counter').textContent=`Aufgabe ${state.index+1} von ${state.tasks.length}`;$('#points').textContent=state.points;$('#streak').textContent=state.streak;$('#progress-bar').style.width=`${state.index/state.tasks.length*100}%`;$('#feedback').hidden=true;$('#next-task').disabled=false;$('#next-task').textContent=state.index>=state.tasks.length-1?'Fertig →':'Nächste Übung →';$('#hint').textContent='💡 Hilfe';$('#task-card').innerHTML=taskMarkup(t);attachTaskEvents()}
function taskMarkup(t){const eq=`${t.a} × ${t.b}`;if(t.type==='choice')return `<span class="task-label">Wähle das richtige Ergebnis</span><div class="equation">${eq} = ?</div><div class="option-grid">${shuffle([t.result,t.result+7,t.result-6,t.result+10]).map(n=>`<button class="option" data-answer="${n}" type="button">${n}</button>`).join('')}</div>`;if(t.type==='missing')return `<span class="task-label">Welche Zahl fehlt?</span><div class="equation">? × ${t.b} = ${t.result}</div><div class="answer-row"><input class="answer-input" inputmode="numeric" aria-label="Fehlender Faktor"><button class="primary check-answer" type="button">Prüfen</button></div>`;if(t.type==='truefalse'){const truth=Math.random()>.5; t.display=truth?t.result:t.result+2; t.truth=truth;return `<span class="task-label">Wahr oder falsch?</span><div class="equation">${eq} = ${t.display}</div><div class="option-grid"><button class="option" data-answer="true" type="button">👍 Richtig</button><button class="option" data-answer="false" type="button">👎 Falsch</button></div>`}if(t.type==='swap')return `<span class="task-label">Welche Tauschaufgabe gehört dazu?</span><div class="equation">${eq}</div><div class="option-grid"><button class="option" data-answer="${t.b} × ${t.a}" type="button">${t.b} × ${t.a}</button><button class="option" data-answer="${t.a} + ${t.b}" type="button">${t.a} + ${t.b}</button><button class="option" data-answer="${t.b} + ${t.a}" type="button">${t.b} + ${t.a}</button><button class="option" data-answer="${t.a} × ${t.a}" type="button">${t.a} × ${t.a}</button></div>`;return `<span class="task-label">Ergebnis eingeben</span><div class="equation">${eq} = ?</div><div class="answer-row"><input class="answer-input" inputmode="numeric" aria-label="Ergebnis"><button class="primary check-answer" type="button">Prüfen</button></div>`}
function attachTaskEvents(){const t=state.tasks[state.index];const input=$('#task-card .answer-input');const check=$('#task-card .check-answer');$$('#task-card .option').forEach(b=>b.addEventListener('click',()=>answer(b.dataset.answer,t)));check?.addEventListener('click',()=>answer(input.value,t));input?.addEventListener('keydown',e=>{if(e.key==='Enter')check.click()})}
function answer(value,t){if(state.answered)return;let expected=t.type==='truefalse'?String(t.truth):t.type==='swap'?`${t.b} × ${t.a}`:t.type==='missing'?String(t.a):String(t.result);const submitted=String(value).trim();const ok=submitted===expected||submitted===String(t.result);state.answered=ok;updateStat(t,ok);const f=$('#feedback');f.hidden=false;f.className=`feedback ${ok?'good':'bad'}`;if(ok){state.points+=10;state.streak++;f.innerHTML=`✅ Richtig! ${t.a} × ${t.b} = ${t.result}. ${state.streak>=3?'🔥 Serie!':''}`}else{state.streak=0;f.innerHTML=`❌ Noch nicht ganz. ${hintText(t,1)} Du kannst trotzdem weitergehen oder dir die Lösung anzeigen lassen.`}$('#points').textContent=state.points;$('#streak').textContent=state.streak;$('#next-task').disabled=false;save()}
function hintText(t,level){const base=t.a>5?`Kennst du 5 × ${t.b}?`:`Nutze die ${t.a}er-Reihe.`;if(level===1)return `💡 Tipp: ${base}`;if(level===2)return `💡 ${5*t.b} + ${(t.a-5)*t.b} = ?`;return `💡 ${t.a} × ${t.b} = ${t.result}`}
function nextTask(){if(state.index>=state.tasks.length-1){$('#feedback').textContent+=` · ${state.points} Punkte`;$('#next-task').textContent='Noch einmal';$('#next-task').onclick=()=>startPractice(state.series);return}state.index++;renderTask();attachTaskEvents()}
function showHint(){const t=state.tasks[state.index];state.hint=Math.min(state.hint+1,3);const f=$('#feedback');f.hidden=false;f.className='feedback';f.textContent=hintText(t,state.hint);$('#hint').textContent=state.hint===3?'✅ Lösung gezeigt':'💡 Hilfe'}
function showSolution(){const t=state.tasks[state.index];state.answered=true;const f=$('#feedback');f.hidden=false;f.className='feedback good';f.textContent=t.type==='swap'?`✅ Lösung: Die Tauschaufgabe zu ${t.a} × ${t.b} ist ${t.b} × ${t.a}. Beide ergeben ${t.result}.`:`✅ Lösung: ${t.a} × ${t.b} = ${t.result}.`;$('#next-task').disabled=false}
function startDuel(){state.duel={player:0,computer:0};newDuelTask()}
function newDuelTask(){const t=makeTasks('all',1)[0];$('#duel-area').innerHTML=taskMarkup({...t,type:'choice'});$('#duel-feedback').hidden=true;$('#duel-next').disabled=true;$$('#duel-area .option').forEach(b=>b.addEventListener('click',()=>{const ok=b.dataset.answer===String(t.result);if(ok)state.duel.player++;if(Math.random()>.55)state.duel.computer++;$('#player-score').textContent=state.duel.player;$('#computer-score').textContent=state.duel.computer;$('#duel-feedback').hidden=false;$('#duel-feedback').className=`feedback ${ok?'good':'bad'}`;$('#duel-feedback').textContent=ok?'✅ Punkt für dich!':'💡 Kein Punkt – der Computer übt auch.';$('#duel-next').disabled=false}))}
function startChallenge(){state.tasks=makeTasks('all',20);state.index=0;state.points=0;state.challenge=true;$('#challenge-start').hidden=true;$('#challenge-result').hidden=true;$('#challenge-area').hidden=false;renderChallenge()}
function renderChallenge(){const t=state.tasks[state.index];state.answered=false;$('#challenge-counter').textContent=`Aufgabe ${state.index+1} von 20`;$('#challenge-points').textContent=state.points;$('#challenge-bar').style.width=`${state.index/20*100}%`;$('#challenge-feedback').hidden=true;$('#challenge-next').disabled=true;$('#challenge-card').innerHTML=taskMarkup({...t,type:state.index%3===0?'choice':state.index%3===1?'input':'swap'});const input=$('#challenge-card .answer-input');$('#challenge-card .check-answer')?.addEventListener('click',()=>challengeAnswer(input.value,t));input?.addEventListener('keydown',e=>{if(e.key==='Enter')challengeAnswer(input.value,t)});$$('#challenge-card .option').forEach(b=>b.addEventListener('click',()=>challengeAnswer(b.dataset.answer,t)))}
function challengeAnswer(value,t){if(state.answered)return;state.answered=true;const ok=String(value).trim()===String(t.result)||String(value).trim()===`${t.b} × ${t.a}`;const f=$('#challenge-feedback');f.hidden=false;f.className=`feedback ${ok?'good':'bad'}`;f.textContent=ok?'✅ Richtig! +10 Punkte':`❌ Die Lösung ist ${t.result}.`;if(ok)state.points+=10;$('#challenge-points').textContent=state.points;$('#challenge-next').disabled=false}
function finishChallenge(){const correct=state.points/10;$('#challenge-area').hidden=true;$('#challenge-result').hidden=false;$('#challenge-result').innerHTML=`<p class="kicker">GESCHAFFT</p><h2>Dein Ergebnis</h2><p class="result-stat">✅ Richtig: <strong>${correct} / 20</strong></p><p class="result-stat">⭐ Punkte: <strong>${state.points}</strong></p><p class="result-stat">🎯 Trefferquote: <strong>${correct*5}%</strong></p><p>${correct>=16?'Stark! Du bist auf dem Weg zum Einmaleins-Profi.':'Guter Start – trainiere die Reihen mit den meisten Fehlern weiter.'}</p><button class="primary" id="restart-challenge">Noch einmal</button>`;$('#restart-challenge').addEventListener('click',startChallenge)}
function renderTable(){let html='<button class="header" aria-label="Leer">×</button>';for(let n=1;n<=10;n++)html+=`<button class="header">${n}</button>`;for(let a=1;a<=10;a++){html+=`<button class="header">${a}</button>`;for(let b=1;b<=10;b++)html+=`<button data-a="${a}" data-b="${b}">${a*b}</button>`}$('#times-table').innerHTML=html;$$('#times-table button[data-a]').forEach(b=>b.addEventListener('click',()=>{const a=Number(b.dataset.a),c=Number(b.dataset.b);$$('#times-table button').forEach(x=>x.classList.remove('selected','paired'));b.classList.add('selected');$(`#times-table button[data-a="${c}"][data-b="${a}"]`)?.classList.add('paired');$('#table-detail').textContent=`${a} × ${c} = ${a*c} · ${c} × ${a} = ${a*c}`}))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;const view=b.dataset.view;if(view==='practice'){show('practice');if(b.dataset.series){$('#practice-picker').hidden=false;$('#task-area').hidden=true}}else if(view==='duel'){show('duel');startDuel()}else show(view)});
$('#learn-prev').addEventListener('click',()=>{state.index=(state.index+learnCards.length-1)%learnCards.length;renderLearn()});$('#learn-next').addEventListener('click',()=>{state.index=(state.index+1)%learnCards.length;renderLearn()});$('#hint').addEventListener('click',showHint);$('#show-solution').addEventListener('click',showSolution);$('#next-task').addEventListener('click',nextTask);$('#start-challenge').addEventListener('click',startChallenge);$('#challenge-next').addEventListener('click',()=>{if(state.index>=19)finishChallenge();else{state.index++;state.answered=false;renderChallenge()}});$('#duel-next').addEventListener('click',newDuelTask);$('#theme-toggle').addEventListener('click',()=>{document.body.classList.toggle('dark');$('#theme-toggle').textContent=document.body.classList.contains('dark')?'🌙':'☀️';localStorage.setItem('linguacode-theme',document.body.classList.contains('dark')?'dark':'light')});
renderSeries('#series-grid',(s)=>{show('practice');startPractice(s)});renderSeries('#practice-series',(s)=>startPractice(s));if(localStorage.getItem('linguacode-theme')==='dark'){document.body.classList.add('dark');$('#theme-toggle').textContent='🌙'}renderMastery();renderLearn();
