import {sets,parseCards,shuffle,quizOptions,grade,summarize,readProgress,simulate,bubbleStep} from './core.mjs';
const $=id=>document.getElementById(id);
let cards=[],deck=[],position=0,revealed=false,answered=false,progress={},session={},simValues=[],simStep=0,stack=[],queue=[];
let storage;try{storage=localStorage;progress=readProgress(storage);}catch{}
function save(){try{storage?.setItem('linguacode-java-cards-v1',JSON.stringify(progress));}catch{$('feedback').textContent='Speichern nicht möglich. Dein Lernstand gilt nur für diese Sitzung.';}}
function updateStats(){const ids=deck.map(c=>c.id),stats=summarize(ids,progress),current=summarize(ids,session);$('progress').max=ids.length||1;$('progress').value=stats.known;$('summary').textContent=`${stats.known} gewusst · ${stats.practice} noch üben · ${ids.length-stats.known-stats.practice} offen (aktueller Satz).`;$('session').textContent=`Diese Sitzung: ${current.known} gewusst · ${current.practice} noch üben. ${current.known+current.practice===ids.length&&ids.length?'Satz vollständig bewertet.':''}`;}
function button(text,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',action);return b;}
function highlight(code){$('code').replaceChildren();const pattern=/(\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:\\.|[^"\\])*"|\b(?:public|private|protected|class|static|void|int|boolean|double|new|return|if|else|for|while|true|false|null|extends|this|String)\b|\b\d+\b)/g;let cursor=0;for(const match of code.matchAll(pattern)){$('code').append(document.createTextNode(code.slice(cursor,match.index)));const span=document.createElement('span');span.textContent=match[0];span.className='token-'+(match[0].startsWith('/')?'comment':match[0].startsWith('"')?'string':/^\d/.test(match[0])?'number':'keyword');$('code').append(span);cursor=match.index+match[0].length;}$('code').append(document.createTextNode(code.slice(cursor)));}
function reveal(){if(!deck.length||revealed||($('mode').value==='quiz'&&quizOptions(deck[position])&&!answered))return;revealed=true;$('simulation').hidden=deck[position].type!=='simulation';$('answer-panel').hidden=false;$('reveal').hidden=true;$('known').disabled=false;$('practice').disabled=false;}
function rate(value){if(!revealed)return;const id=deck[position].id;progress[id]=value;session[id]=value;save();updateStats();$('known').disabled=true;$('practice').disabled=true;$('feedback').textContent+=(value==='known'?' Gewusst gespeichert.':' Noch üben gespeichert.');}
function configureSim(card){simValues=[5,1,4,2];simStep=0;stack=[];queue=[];$('sim-output').textContent='';$('sim-input').value=({53:'2, 4, 6',62:'4',65:'10',76:'16'})[card.id]||'';$('sim-instructions').textContent=card.interaction;$('sim-label').hidden=card.id===68;$('sim-run').hidden=card.id===72;$('sim-add').hidden=card.id!==72;$('sim-remove').hidden=card.id!==72;$('sim-run').disabled=false;$('sim-run').textContent=card.id===68?'Nächster Sortierschritt':'Berechnen';if(card.id===68)$('sim-output').textContent=simValues.join(' · ');}
function render(){revealed=false;answered=false;$('answer-panel').hidden=true;$('answer').textContent='';$('quiz').replaceChildren();$('feedback').textContent='';$('known').disabled=true;$('practice').disabled=true;$('reveal').hidden=false;$('card').hidden=!deck.length;$('prev').disabled=position===0;$('next').disabled=position>=deck.length-1;updateStats();if(!deck.length){$('status').textContent='Keine Karten in diesem Satz. Wähle mindestens eine Karte.';return;}const card=deck[position];$('status').textContent=`Karte ${position+1} von ${deck.length}`;$('meta').textContent=`Nr. ${card.id} · ${card.topic}`;$('title').textContent=card.title;$('question').textContent=card.question;$('answer').textContent=card.answer;$('code-panel').hidden=!card.code;highlight(card.code);document.body.classList.toggle('teacher',$('mode').value==='teacher');const options=$('mode').value==='quiz'?quizOptions(card):null;if(options){$('reveal').hidden=true;options.forEach(option=>{$('quiz').append(button(option,()=>{if(answered)return;answered=true;const correct=grade(card,option);reveal();rate(correct?'known':'practice');$('feedback').textContent=correct?'Richtig.':'Noch üben – lies die Erklärung.';[...$('quiz').children].forEach(b=>b.disabled=true);}));});}else if($('mode').value==='quiz'){$('feedback').textContent='Offene Frage: Erst selbst beantworten, dann aufdecken und ehrlich einschätzen.';}$('simulation').hidden=card.type!=='simulation'||$('mode').value==='quiz';if(card.type==='simulation')configureSim(card);}
function chooseDeck(){const set=$('set').value;if(set==='custom')return;deck=set==='all'?[...cards]:cards.filter(c=>c.id>=sets[Number(set)][0]&&c.id<=sets[Number(set)][1]);if($('mode').value==='challenge')deck=deck.filter(c=>c.type==='simulation');position=0;render();}
function move(delta){const next=position+delta;if(next<0||next>=deck.length)return;position=next;render();}
$('set').addEventListener('change',()=>{$('custom').hidden=$('set').value!=='custom';chooseDeck();});
$('mode').addEventListener('change',()=>{$('set').value==='custom'?applySelection():chooseDeck();});
$('shuffle').addEventListener('click',()=>{deck=shuffle(deck);position=0;render();});
function applySelection(){const ids=[...$('choices').children].filter(label=>label.children[0].checked).map(label=>Number(label.children[0].value));deck=cards.filter(c=>ids.includes(c.id)&&($('mode').value!=='challenge'||c.type==='simulation'));position=0;render();}
$('apply').addEventListener('click',applySelection);$('reveal').addEventListener('click',reveal);$('known').addEventListener('click',()=>rate('known'));$('practice').addEventListener('click',()=>rate('practice'));$('prev').addEventListener('click',()=>move(-1));$('next').addEventListener('click',()=>move(1));
$('reset').addEventListener('click',()=>{if(window.confirm('Deinen lokal gespeicherten Java-Lernstand zurücksetzen?')){progress={};session={};save();render();}});
$('sim-run').addEventListener('click',()=>{try{const card=deck[position];if(card.id===68){const result=bubbleStep(simValues,simStep++);simValues=result.values;$('sim-output').textContent=simValues.join(' · ')+' — '+result.detail;$('sim-run').disabled=result.done;}else $('sim-output').textContent=simulate(card.id,$('sim-input').value);}catch(error){$('sim-output').textContent=error.message;}});
function showStructures(detail){$('sim-output').textContent=`${detail} Stack (oben rechts): [${stack.join(', ')}] · Queue (vorn links): [${queue.join(', ')}]`;}
$('sim-add').addEventListener('click',()=>{const value=$('sim-input').value.trim();if(!value||value.length>20||stack.length>=10){showStructures('1–20 Zeichen eingeben, höchstens 10 Elemente.');return;}stack.push(value);queue.push(value);showStructures('Hinzugefügt.');});
$('sim-remove').addEventListener('click',()=>showStructures(stack.length?`Entfernt: Stack ${stack.pop()} · Queue ${queue.shift()}.`:'Beide Strukturen sind leer.'));
$('sim-reset').addEventListener('click',()=>configureSim(deck[position]));
window.addEventListener('keydown',event=>{if(event.target.closest('input,select,textarea,button,a')||event.target.isContentEditable||event.altKey||event.ctrlKey||event.metaKey)return;if(['ArrowRight','ArrowLeft',' '].includes(event.key)){event.preventDefault();if(event.key===' ')reveal();else move(event.key==='ArrowRight'?1:-1);}});
async function init(){try{const response=await fetch('cards.md');if(!response.ok)throw new Error('Datei nicht erreichbar');cards=parseCards(await response.text());sets.forEach((set,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=`${set[0]}–${set[1]} · ${set[2]}`;$('set').append(option);});cards.forEach(card=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=String(card.id);label.append(input,document.createTextNode(`${card.id} · ${card.title}`));$('choices').append(label);});chooseDeck();}catch(error){$('status').textContent='Lernkartei konnte nicht geladen werden. Bitte neu laden. '+error.message;}}
await init();
