/* Pretérito imperfecto: regelmäßige Verben, lokal und ohne Schülerdaten. */
(() => {
  'use strict';
  const app = document.querySelector('#app');
  const scoreEl = document.querySelector('#score');
  const levelBadge = document.querySelector('#level-badge');
  const progressBar = document.querySelector('#progress-bar');
  const progressValue = document.querySelector('#progress-value');
  const progressTitle = document.querySelector('#progress-title');
  const storageKey = 'linguacode-imperfecto-mastery-v1';
  const groups = { ar: ['aba','abas','aba','ábamos','abais','aban'], er: ['ía','ías','ía','íamos','íais','ían'], ir: ['ía','ías','ía','íamos','íais','ían'] };
  const persons = { yo:0, tú:1, él:2, ella:2, usted:2, nosotros:3, nosotras:3, vosotros:4, vosotras:4, ellos:5, ellas:5, ustedes:5 };
  const level1 = [
    {kind:'input', verb:'hablar', group:'ar', person:'yo', answer:'hablaba'},
    {kind:'ending', stem:'habl', group:'ar', person:'nosotros', answer:'ábamos'},
    {kind:'choice', prompt:'vivir + vosotros', group:'ir', person:'vosotros', options:['vivían','vivíais','vivíamos','vivías'], answer:1, key:'ir-vosotros'},
    {kind:'error', sentence:'Nosotros comían.', group:'er', person:'nosotros', answer:'comíamos', explanation:'Nosotros braucht bei -ER die Endung -íamos: comíamos.'},
    {kind:'compose', stem:'com', group:'er', person:'nosotros', answer:'íamos'},
    {kind:'input', verb:'vivir', group:'ir', person:'ellos', answer:'vivían'},
    {kind:'ending', stem:'bail', group:'ar', person:'vosotros', answer:'abais'},
    {kind:'choice', prompt:'comer + tú', group:'er', person:'tú', options:['comía','comías','comíamos','comían'], answer:1, key:'er-tú'},
    {kind:'input', verb:'estudiar', group:'ar', person:'nosotras', answer:'estudiábamos'},
    {kind:'error', sentence:'Ellos vivían.', group:'ir', person:'ellos', answer:'correcto', explanation:'Richtig: ellos bei -IR endet auf -ían.'}
  ];
  const level2 = [
    {kind:'input', icon:'⚽', signal:'De pequeño', sentence:'De pequeño, yo ___ mucho con mis amigos.', verb:'jugar', group:'ar', person:'yo', answer:'jugaba'},
    {kind:'input', icon:'🏠', signal:'Antes', sentence:'Antes nosotros ___ en Bonn.', verb:'vivir', group:'ir', person:'nosotros', answer:'vivíamos'},
    {kind:'choice', icon:'✈️', signal:'Todos los veranos', sentence:'Todos los veranos mis padres ___ a España.', group:'ar', person:'ellos', options:['viajaba','viajabas','viajábamos','viajaban'], answer:3, key:'ar-ellos'},
    {kind:'input', icon:'🎵', sentence:'Mi hermana y yo ___ mucha música.', verb:'escuchar', group:'ar', person:'nosotros', answer:'escuchábamos'},
    {kind:'input', icon:'🏃', signal:'De pequeño', sentence:'De pequeño, tú ___ mucho deporte.', verb:'practicar', group:'ar', person:'tú', answer:'practicabas'},
    {kind:'choice', icon:'🍽️', signal:'Los fines de semana', sentence:'Los fines de semana ellos ___ con sus amigos.', group:'er', person:'ellos', options:['comía','comías','comíais','comían'], answer:3, key:'er-ellos'},
    {kind:'input', icon:'👥', sentence:'Mi hermano ___ mucho con sus amigos.', verb:'hablar', group:'ar', person:'él', answer:'hablaba'},
    {kind:'choice', icon:'📚', signal:'Normalmente', sentence:'Normalmente mis amigos y yo ___ en casa.', group:'ar', person:'nosotros', options:['estudiaba','estudiábamos','estudiabais','estudiaban'], answer:1, key:'ar-nosotros'},
    {kind:'input', icon:'📺', signal:'Cada día', sentence:'Cada día ellas ___ la televisión.', verb:'mirar', group:'ar', person:'ellas', answer:'miraban'},
    {kind:'input', icon:'💃', signal:'Siempre', sentence:'Siempre vosotros ___ después de clase.', verb:'bailar', group:'ar', person:'vosotros', answer:'bailabais'},
    {kind:'choice', icon:'🎵', signal:'A menudo', sentence:'A menudo yo ___ música.', group:'ar', person:'yo', options:['escuchaba','escuchabas','escuchábamos','escuchaban'], answer:0, key:'ar-yo'},
    {kind:'input', icon:'🍽️', signal:'Todos los domingos', sentence:'Todos los domingos nosotros ___ juntos.', verb:'comer', group:'er', person:'nosotros', answer:'comíamos'}
  ];
  const state = { screen:'intro', index:0, score:0, attempts:{}, mistakes:{}, level1Score:0, challengeScore:0 };
  const saved = JSON.parse(localStorage.getItem(storageKey) || '{}');
  const mistakeKey = (group, person) => `${group}-${person}`;
  const save = () => localStorage.setItem(storageKey, JSON.stringify({ mistakes:state.mistakes, level1Done:state.level1Score === level1.length }));
  const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const normalize = (value) => value.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const conjugation = (item) => { const stem = item.verb.slice(0,-2); return stem + groups[item.group][persons[item.person]]; };
  const ending = (item) => groups[item.group][persons[item.person]];
  const setProgress = (title, current, total) => { const percent = Math.round((current / total) * 100); progressTitle.textContent = title; progressValue.textContent = `${percent} %`; progressBar.style.width = `${percent}%`; };
  const updateHeader = () => { scoreEl.textContent = `${state.score} Punkte`; levelBadge.textContent = state.screen === 'level2' || state.screen === 'challenge' ? '⭐⭐ Level 2' : '⭐ Level 1'; };
  const shell = (eyebrow, title, body, nextLabel) => { app.innerHTML = `<section class="screen"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${body}${nextLabel ? `<div class="next-row"><button id="next">${nextLabel}</button></div>` : ''}</section>`; document.querySelector('#next')?.addEventListener('click', next); updateHeader(); };
  const playTone = (correct) => { const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; const audio = new AudioContext(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.type = 'sine'; oscillator.frequency.setValueAtTime(correct ? 740 : 190, audio.currentTime); oscillator.frequency.exponentialRampToValueAtTime(correct ? 1040 : 120, audio.currentTime + .18); gain.gain.setValueAtTime(.0001, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.16, audio.currentTime + .015); gain.gain.exponentialRampToValueAtTime(.0001, audio.currentTime + .22); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .24); oscillator.addEventListener('ended', () => audio.close(), { once:true }); };
  const showAnswerOverlay = (correct) => { document.querySelector('.answer-overlay')?.remove(); const overlay = document.createElement('div'); overlay.className = `answer-overlay ${correct ? 'is-correct' : 'is-wrong'}`; overlay.setAttribute('role','status'); overlay.setAttribute('aria-live','assertive'); overlay.innerHTML = `<strong>${correct ? 'Correcto' : 'Intenta de nuevo'}</strong>`; document.body.append(overlay); playTone(correct); window.setTimeout(() => overlay.remove(), 850); };
  const markMistake = (item) => { if (item.group && item.person) { const key = mistakeKey(item.group,item.person); state.mistakes[key] = (state.mistakes[key] || 0) + 1; save(); } };
  const level2Tasks = () => { const priority = (item) => item.group && item.person ? (state.mistakes[mistakeKey(item.group,item.person)] || 0) : 0; return [...level2].sort((a,b) => priority(b) - priority(a)); };
  const showHint = (item, stage) => { const target = document.querySelector('#hint'); if (!target) return; const hints = item.group ? [`💡 Tipp 1: ${item.verb ? `Erkenne die Verbgruppe: ${item.verb} ist ein -${item.group.toUpperCase()}-Verb.` : 'Erkenne zuerst die Verbgruppe.'}`, `💡 Tipp 2: Die Person ist <strong>${esc(item.person)}</strong>.`, `💡 Tipp 3: Für diese Person brauchst du die Endung <strong>-${esc(ending(item))}</strong>.`, `💡 Tipp 4: ${item.verb ? `${esc(item.verb.slice(0,-2))} + ______` : `${esc(item.stem)} + ______`}`] : ['💡 Tipp 1: Markiere die Person im Satz.', '💡 Tipp 2: Finde die Verbgruppe des Infinitivs.', '💡 Tipp 3: Wähle die passende Imperfecto-Endung.', '💡 Tipp 4: Setze Stamm und Endung zusammen.']; target.innerHTML = `<strong>${hints[Math.min(stage,3)]}</strong>`; target.hidden = false; };
  const check = (item, value, onCorrect) => { const key = `${state.screen}-${state.index}`; const used = state.attempts[key] || 0; if (used >= 3) return; state.attempts[key] = used + 1; const ok = normalize(value) === normalize(item.answer); const feedback = document.querySelector('#feedback'); showAnswerOverlay(ok); if (ok) { state.score += 1; if (state.screen === 'level1') state.level1Score += 1; feedback.className = 'feedback good'; feedback.innerHTML = '✅ ¡Muy bien!'; onCorrect?.(); setTimeout(next, 650); } else { markMistake(item); feedback.className = 'feedback bad'; feedback.innerHTML = used === 0 ? 'Noch nicht. Nutze den ersten Tipp.' : used === 1 ? 'Fast – prüfe Person und Endung.' : `Die Lösung ist <strong>${esc(item.answer)}</strong>.`; showHint(item, used); if (used >= 2) { onCorrect?.(true); setTimeout(next, 1100); } } updateHeader(); save(); };
  const inputTask = (item) => { const text = item.sentence ? item.sentence.replace('___','<span class="blank">?</span>') : `${esc(item.verb)} + <strong>${esc(item.person)}</strong>`; return `<div class="task-card"><p class="prompt">${item.icon || ''} ${item.signal ? `<span class="context-signal">${esc(item.signal)}</span> ` : ''}${text}</p>${item.verb ? `<p class="small">Infinitiv: <strong>${esc(item.verb)}</strong></p>` : ''}<div class="answer-line"><label class="sr-only" for="answer">Deine Antwort</label><input id="answer" class="answer-input" autocomplete="off" spellcheck="false" placeholder="Form eingeben …"><button id="check">Prüfen</button></div><p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`; };
  const choiceTask = (item) => `<div class="task-card"><p class="prompt">${item.icon || ''} ${item.signal ? `<span class="context-signal">${esc(item.signal)}</span> ` : ''}${esc(item.sentence || item.prompt)}</p><div class="choices">${item.options.map((option,index) => `<button data-choice="${index}">${String.fromCharCode(65+index)}) ${esc(option)}</button>`).join('')}</div><p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`;
  const errorTask = (item) => `<div class="task-card"><p class="prompt">„${esc(item.sentence)}“</p><div class="choices"><button data-choice="correcto">✅ Correcto</button><button data-choice="incorrecto">❌ Incorrecto</button></div><p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div><div id="explanation" class="explanation" hidden>${esc(item.explanation)}</div></div>`;
  const composeTask = (item) => `<div class="task-card"><p class="prompt">${esc(item.stem)} + <span class="blank">______</span></p><p class="small">${esc(item.person)} · -${item.group.toUpperCase()}-Verb</p><div class="answer-line"><input id="answer" class="answer-input" autocomplete="off" spellcheck="false" placeholder="Endung eingeben …"><button id="check">Prüfen</button></div><p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`;
  function renderTask(items, title) { const item = items[state.index]; setProgress(title, state.index, items.length); const task = item.kind === 'input' ? inputTask(item) : item.kind === 'choice' ? choiceTask(item) : item.kind === 'error' ? errorTask(item) : composeTask(item); shell(title, `${state.screen === 'level1' ? 'Konjugieren' : 'Im Kontext'} · Aufgabe ${state.index+1}`, task); if (item.kind === 'input' || item.kind === 'compose') { document.querySelector('#check').onclick = () => check(item, document.querySelector('#answer').value, (exhausted) => { if (exhausted) document.querySelector('#answer').disabled = true; }); document.querySelector('#answer').addEventListener('keydown', (event) => { if (event.key === 'Enter') document.querySelector('#check').click(); }); } else { document.querySelectorAll('[data-choice]').forEach(button => button.onclick = () => { const value = item.kind === 'error' ? button.dataset.choice : item.options[+button.dataset.choice]; check({...item, answer:item.kind === 'error' ? (item.answer === 'correcto' ? 'correcto' : 'incorrecto') : item.options[item.answer]}, value, () => { document.querySelectorAll('[data-choice]').forEach((b) => { b.disabled = true; }); document.querySelector('#explanation')?.removeAttribute('hidden'); }); }); } }
  function intro() { setProgress('Start',0,1); shell('Pretérito imperfecto', 'Erkennen → bilden → anwenden', `<p class="lead">Du lernst zuerst die Formen regelmäßiger <strong>-AR</strong>-, <strong>-ER</strong>- und <strong>-IR</strong>-Verben. Danach setzt du sie in kurzen Alltagssätzen ein.</p><div class="level-map"><div class="level-node active">⭐ Level 1<br><small>Formen bilden</small></div><div class="level-arrow">→</div><div class="level-node">⭐⭐ Level 2<br><small>Im Kontext</small></div></div><div class="panel"><h2>Merke</h2><p>Im Level 2 kommen weiterhin <strong>ausschließlich regelmäßige Verben</strong> vor.</p><p class="rule">Stamm + Endung = Imperfecto</p><div class="icon-row"><span class="icon-chip">⚽ jugar</span><span class="icon-chip">📚 estudiar</span><span class="icon-chip">🏠 vivir</span><span class="icon-chip">🍽️ comer</span></div></div>`, 'Level 1 starten →'); }
  function startLevel1() { state.screen='level1'; state.index=0; state.score=0; state.attempts={}; renderTask(level1,'Level 1 · Formen bilden'); }
  function level1Done() { state.screen='level1done'; setProgress('Level 1 abgeschlossen',level1.length,level1.length); shell('✅ Level 1 abgeschlossen', 'Du kannst die Formen bilden.', `<div class="panel"><p class="lead">Stark! Jetzt brauchst du die Formen in kurzen Sätzen.</p><div class="level-map"><div class="level-node active">✅ Formen bilden</div><div class="level-arrow">↓</div><div class="level-node">⭐ Anwendung</div></div><p>Deine Fehler aus Level 1 werden in Level 2 gezielt wiederholt.</p></div>`, 'Weiter zu Level 2 – Anwendung →'); }
  function startLevel2() { state.screen='level2'; state.index=0; state.score=0; state.attempts={}; state.level2Items=level2Tasks(); renderTask(state.level2Items,'Level 2 · Anwendung im Kontext'); }
  function miniChallenge() { state.screen='challenge'; state.index=0; state.challengeScore=0; setProgress('Mini-Challenge',0,5); const items=[['De pequeño yo ___ mucho con mis amigos.','hablar','hablaba'],['Mi familia y yo ___ en una casa pequeña.','vivir','vivíamos'],['Todos los domingos nosotros ___ juntos.','comer','comíamos'],['Mis amigos ___ mucho deporte.','practicar','practicaban'],['En verano yo ___ a España.','viajar','viajaba']]; shell('🔥 MINI-CHALLENGE', 'Mi vida antes', `<p class="lead">Fünf kurze Sätze – diesmal ohne direkte Tipps.</p><div class="challenge-list">${items.map((item,index) => `<div class="challenge-row"><p>${index+1}. ${esc(item[0])}</p><small>(${esc(item[1])})</small><input class="answer-input" data-challenge="${index}" autocomplete="off" spellcheck="false" placeholder="Deine Lösung"></div>`).join('')}</div><p id="challenge-feedback" class="feedback"></p><div class="next-row"><button id="finish-challenge">Auswerten</button></div>`); document.querySelector('#finish-challenge').onclick = () => { state.challengeScore = items.reduce((sum,item,index) => sum + (normalize(document.querySelector(`[data-challenge="${index}"]`).value) === item[2] ? 1 : 0),0); document.querySelectorAll('[data-challenge]').forEach(input => { input.disabled=true; }); document.querySelector('#finish-challenge').disabled=true; document.querySelector('#challenge-feedback').textContent=`${state.challengeScore} / 5`; setTimeout(finish,500); }; }
  function finish() { state.screen='finish'; setProgress('Abgeschlossen',1,1); const result=state.challengeScore; const message=result===5?'🏆 ¡Excelente!':result===4?'👏 ¡Muy bien!':result===3?'👍 ¡Bien! Repasa algunas terminaciones.':'📖 Schau dir die Regeln noch einmal an.'; shell('Level 2 abgeschlossen', 'Du hast angewendet!', `<div class="finish"><p class="result">${result} / 5</p><h2>${message}</h2><p>Du hast den Weg von der Form zur echten Anwendung geschafft.</p><p class="rule">ERKENNEN → BILDEN → ANWENDEN</p></div>`, 'Noch einmal starten'); }
  function next() { if(state.screen==='intro') return startLevel1(); if(state.screen==='level1') { if(state.index < level1.length-1) { state.index += 1; return renderTask(level1,'Level 1 · Formen bilden'); } return level1Done(); } if(state.screen==='level1done') return startLevel2(); if(state.screen==='level2') { if(state.index < state.level2Items.length-1) { state.index += 1; return renderTask(state.level2Items,'Level 2 · Anwendung im Kontext'); } return miniChallenge(); } if(state.screen==='finish') { state.screen='intro'; state.index=0; state.score=0; state.challengeScore=0; return intro(); } }
  state.mistakes = saved.mistakes || {}; intro();
})();
