/* Pretérito imperfecto: regelmäßige Verben, lokal und ohne Schülerdaten. */
(() => {
  'use strict';
  const app = document.querySelector('#app');
  const scoreEl = document.querySelector('#score');
  const levelBadge = document.querySelector('#level-badge');
  const progressBar = document.querySelector('#progress-bar');
  const progressValue = document.querySelector('#progress-value');
  const progressTitle = document.querySelector('#progress-title');
  const storageKey = 'linguacode-imperfecto-mastery-v1';
  const groups = { ar: ['aba','abas','aba','ábamos','abais','aban'], er: ['ía','ías','ía','íamos','íais','ían'], ir: ['ía','ías','ía','íamos','íais','ían'] };
  const irregularStems = { ser:'er', 'irregular-ir':'ib', ver:'ve' };
  const persons = { yo:0, tú:1, él:2, ella:2, usted:2, nosotros:3, nosotras:3, vosotros:4, vosotras:4, ellos:5, ellas:5, ustedes:5 };
  const level1 = [
    {kind:'input', verb:'hablar', group:'ar', person:'yo', answer:'hablaba'},
    {kind:'ending', stem:'habl', group:'ar', person:'nosotros', answer:'ábamos'},
    {kind:'choice', prompt:'vivir + vosotros', group:'ir', person:'vosotros', options:['vivían','vivíais','vivíamos','vivías'], answer:1, key:'ir-vosotros'},
    {kind:'error', sentence:'Nosotros comían.', group:'er', person:'nosotros', answer:'comíamos', explanation:'Nosotros braucht bei -ER die Endung -íamos: comíamos.'},
    {kind:'compose', stem:'com', group:'er', person:'nosotros', answer:'íamos'},
    {kind:'input', verb:'vivir', group:'ir', person:'ellos', answer:'vivían'},
    {kind:'ending', stem:'bail', group:'ar', person:'vosotros', answer:'abais'},
    {kind:'choice', prompt:'comer + tú', group:'er', person:'tú', options:['comía','comías','comíamos','comían'], answer:1, key:'er-tú'},
    {kind:'input', verb:'estudiar', group:'ar', person:'nosotras', answer:'estudiábamos'},
    {kind:'error', sentence:'Ellos vivían.', group:'ir', person:'ellos', answer:'correcto', explanation:'Richtig: ellos bei -IR endet auf -ían.'}
  ];
  const level2 = [
    {kind:'input', icon:'⚽', signal:'De pequeño', sentence:'De pequeño, yo ___ mucho con mis amigos.', verb:'jugar', group:'ar', person:'yo', answer:'jugaba'},
    {kind:'input', icon:'🏠', signal:'Antes', sentence:'Antes nosotros ___ en Bonn.', verb:'vivir', group:'ir', person:'nosotros', answer:'vivíamos'},
    {kind:'choice', icon:'✈️', signal:'Todos los veranos', sentence:'Todos los veranos mis padres ___ a España.', group:'ar', person:'ellos', options:['viajaba','viajabas','viajábamos','viajaban'], answer:3, key:'ar-ellos'},
    {kind:'input', icon:'🎵', sentence:'Mi hermana y yo ___ mucha música.', verb:'escuchar', group:'ar', person:'nosotros', answer:'escuchábamos'},
    {kind:'input', icon:'🏃', signal:'De pequeño', sentence:'De pequeño, tú ___ mucho deporte.', verb:'practicar', group:'ar', person:'tú', answer:'practicabas'},
    {kind:'choice', icon:'🍽️', signal:'Los fines de semana', sentence:'Los fines de semana ellos ___ con sus amigos.', group:'er', person:'ellos', options:['comía','comías','comíais','comían'], answer:3, key:'er-ellos'},
    {kind:'input', icon:'👥', sentence:'Mi hermano ___ mucho con sus amigos.', verb:'hablar', group:'ar', person:'él', answer:'hablaba'},
    {kind:'choice', icon:'📚', signal:'Normalmente', sentence:'Normalmente mis amigos y yo ___ en casa.', group:'ar', person:'nosotros', options:['estudiaba','estudiábamos','estudiabais','estudiaban'], answer:1, key:'ar-nosotros'},
    {kind:'input', icon:'📺', signal:'Cada día', sentence:'Cada día ellas ___ la televisión.', verb:'mirar', group:'ar', person:'ellas', answer:'miraban'},
    {kind:'input', icon:'💃', signal:'Siempre', sentence:'Siempre vosotros ___ después de clase.', verb:'bailar', group:'ar', person:'vosotros', answer:'bailabais'},
    {kind:'choice', icon:'🎵', signal:'A menudo', sentence:'A menudo yo ___ música.', group:'ar', person:'yo', options:['escuchaba','escuchabas','escuchábamos','escuchaban'], answer:0, key:'ar-yo'},
    {kind:'input', icon:'🍽️', signal:'Todos los domingos', sentence:'Todos los domingos nosotros ___ juntos.', verb:'comer', group:'er', person:'nosotros', answer:'comíamos'}
  ];
  const level3 = [
    {kind:'input', verb:'ser', irregular:true, group:'ser', person:'yo', answer:'era'},
    {kind:'choice', prompt:'ser + nosotros', irregular:true, group:'ser', person:'nosotros', options:['eran','éramos','erais','era'], answer:1},
    {kind:'input', verb:'ir', irregular:true, group:'irregular-ir', person:'vosotros', answer:'ibais'},
    {kind:'choice', prompt:'ir + ellos', irregular:true, group:'irregular-ir', person:'ellos', options:['iban','ibais','íbamos','iba'], answer:0},
    {kind:'input', verb:'ver', irregular:true, group:'ver', person:'ellas', answer:'veían'},
    {kind:'error', sentence:'Nosotros veíamos la televisión.', irregular:true, group:'ver', person:'nosotros', answer:'correcto', explanation:'Richtig: ver hat im Imperfecto den Stamm ve- und die regelmäßigen -ía-Endungen.'}
  ];
  const level4 = [
    {kind:'input', icon:'🙂', signal:'Antes', sentence:'Antes yo ___ muy tímido.', verb:'ser', irregular:true, group:'ser', person:'yo', answer:'era'},
    {kind:'input', icon:'🏫', signal:'Todos los días', sentence:'Todos los días nosotros ___ al colegio.', verb:'ir', irregular:true, group:'irregular-ir', person:'nosotros', answer:'íbamos'},
    {kind:'choice', icon:'📺', signal:'Por la tarde', sentence:'Por la tarde mi abuela ___ la televisión.', irregular:true, group:'ver', person:'ella', options:['veía','veías','veíamos','veían'], answer:0},
    {kind:'input', icon:'👧', signal:'De pequeños', sentence:'De pequeños, ellos ___ muy alegres.', verb:'ser', irregular:true, group:'ser', person:'ellos', answer:'eran'},
    {kind:'choice', icon:'🚌', signal:'Los lunes', sentence:'Los lunes vosotros ___ juntos al instituto.', irregular:true, group:'irregular-ir', person:'vosotros', options:['iban','ibais','íbamos','iba'], answer:1},
    {kind:'input', icon:'👀', signal:'Siempre', sentence:'Siempre tú ___ muchos vídeos.', verb:'ver', irregular:true, group:'ver', person:'tú', answer:'veías'}
  ];
  const state = { screen:'intro', index:0, score:0, attempts:{}, mistakes:{}, level1Score:0, challengeScore:0, level4Score:0 };
  const saved = JSON.parse(localStorage.getItem(storageKey) || '{}');
  const mistakeKey = (group, person) => `${group}-${person}`;
  const save = () => localStorage.setItem(storageKey, JSON.stringify({ mistakes:state.mistakes, level1Done:state.level1Score === level1.length }));
  const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const normalize = (value) => value.trim().toLowerCase().normalize('NFC');
  const conjugation = (item) => { const stem = item.verb.slice(0,-2); return stem + groups[item.group][persons[item.person]]; };
  const ending = (item) => groups[item.group][persons[item.person]];
  const setProgress = (title, current, total) => { const percent = Math.round((current / total) * 100); progressTitle.textContent = title; progressValue.textContent = `${percent} %`; progressBar.style.width = `${percent}%`; };
  const updateHeader = () => { scoreEl.textContent = `${state.score} Punkte`; levelBadge.textContent = state.screen === 'intro' ? '🎯 Auswahl' : ['level3','level4'].includes(state.screen) ? '⭐⭐⭐ Unregelmäßige Verben' : state.screen === 'level2' || state.screen === 'challenge' ? '⭐⭐ Level 2' : '⭐ Level 1'; };
  const shell = (eyebrow, title, body, nextLabel) => { app.innerHTML = `<section class="screen"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${body}${nextLabel ? `<div class="next-row"><button id="next">${nextLabel}</button></div>` : ''}</section>`; document.querySelector('#next')?.addEventListener('click', next); updateHeader(); };
  const playTone = (correct) => { const AudioContext = window.AudioContext || window.webkitAudioContext; if (!AudioContext) return; const audio = new AudioContext(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.type = 'sine'; oscillator.frequency.setValueAtTime(correct ? 740 : 190, audio.currentTime); oscillator.frequency.exponentialRampToValueAtTime(correct ? 1040 : 120, audio.currentTime + .18); gain.gain.setValueAtTime(.0001, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.16, audio.currentTime + .015); gain.gain.exponentialRampToValueAtTime(.0001, audio.currentTime + .22); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .24); oscillator.addEventListener('ended', () => audio.close(), { once:true }); };
  const showAnswerOverlay = (correct) => { document.querySelector('.answer-overlay')?.remove(); const overlay = document.createElement('div'); overlay.className = `answer-overlay ${correct ? 'is-correct' : 'is-wrong'}`; overlay.setAttribute('role','status'); overlay.setAttribute('aria-live','assertive'); overlay.innerHTML = `<strong>${correct ? 'Correcto' : 'Intenta de nuevo'}</strong>`; document.body.append(overlay); playTone(correct); window.setTimeout(() => overlay.remove(), 850); };
  const markMistake = (item) => { if ((item.group || item.irregular) && item.person) { const key = mistakeKey(item.group || item.irregular,item.person); state.mistakes[key] = (state.mistakes[key] || 0) + 1; save(); } };
  const level2Tasks = () => { const priority = (item) => item.group && item.person ? (state.mistakes[mistakeKey(item.group,item.person)] || 0) : 0; return [...level2].sort((a,b) => priority(b) - priority(a)); };
  const showHint = (item, stage) => { const target = document.querySelector('#hint'); if (!target) return; const hints = item.irregular ? [`💡 Tipp 1: <strong>${esc(item.verb)}</strong> ist unregelmäßig.`, `💡 Tipp 2: Die Person ist <strong>${esc(item.person)}</strong>.`, `💡 Tipp 3: Der besondere Stamm ist <strong>${esc(irregularStems[item.group])}</strong>.`, '💡 Tipp 4: Bilde die vollständige Form mit der passenden Endung.'] : item.group ? [`💡 Tipp 1: ${item.verb ? `Erkenne die Verbgruppe: ${item.verb} ist ein -${item.group.toUpperCase()}-Verb.` : 'Erkenne zuerst die Verbgruppe.'}`, `💡 Tipp 2: Die Person ist <strong>${esc(item.person)}</strong>.`, `💡 Tipp 3: Für diese Person brauchst du die Endung <strong>-${esc(ending(item))}</strong>.`, `💡 Tipp 4: ${item.verb ? `${esc(item.verb.slice(0,-2))} + ______` : `${esc(item.stem)} + ______`}`] : ['💡 Tipp 1: Markiere die Person im Satz.', '💡 Tipp 2: Finde die Verbgruppe des Infinitivs.', '💡 Tipp 3: Wähle die passende Imperfecto-Endung.', '💡 Tipp 4: Setze Stamm und Endung zusammen.']; target.innerHTML = `<strong>${hints[Math.min(stage,3)]}</strong>`; target.hidden = false; };
  const acceptedAnswers = (item) => item.stem ? [item.answer, `${item.stem}${item.answer}`] : [item.answer];
  const skipTask = (item) => { markMistake(item); save(); next(); };
  const check = (item, value, onCorrect) => { const key = `${state.screen}-${state.index}`; const used = state.attempts[key] || 0; if (used >= 3) return; state.attempts[key] = used + 1; const ok = acceptedAnswers(item).some((answer) => normalize(value) === normalize(answer)); const feedback = document.querySelector('#feedback'); showAnswerOverlay(ok); if (ok) { state.score += 1; if (state.screen === 'level1') state.level1Score += 1; feedback.className = 'feedback good'; feedback.innerHTML = '✅ ¡Muy bien!'; onCorrect?.(); setTimeout(next, 650); } else { markMistake(item); feedback.className = 'feedback bad'; feedback.innerHTML = used === 0 ? 'Noch nicht. Nutze den ersten Tipp.' : used === 1 ? 'Fast – prüfe Person und Endung.' : `Die Lösung ist <strong>${esc(item.answer)}</strong>.`; showHint(item, used); if (used >= 2) { onCorrect?.(true); setTimeout(next, 1100); } } updateHeader(); save(); };
  const taskActions = (checkButton = '') => `<div class="task-actions">${checkButton}<button type="button" class="secondary" data-skip>Nächste Übung →</button></div>`;
  const inputTask = (item) => { const text = item.sentence ? item.sentence.replace('___','<span class="blank">?</span>') : `${esc(item.verb)} + <strong>${esc(item.person)}</strong>`; return `<div class="task-card"><p class="prompt">${item.icon || ''} ${item.signal ? `<span class="context-signal">${esc(item.signal)}</span> ` : ''}${text}</p>${item.verb ? `<p class="small">Infinitiv: <strong>${esc(item.verb)}</strong></p>` : ''}<div class="answer-line"><label class="sr-only" for="answer">Deine Antwort</label><input id="answer" class="answer-input" autocomplete="off" spellcheck="false" placeholder="Form eingeben …"></div>${taskActions('<button type="button" id="check">Prüfen</button>')}<p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`; };
  const choiceTask = (item) => `<div class="task-card"><p class="prompt">${item.icon || ''} ${item.signal ? `<span class="context-signal">${esc(item.signal)}</span> ` : ''}${esc(item.sentence || item.prompt)}</p><div class="choices">${item.options.map((option,index) => `<button data-choice="${index}">${String.fromCharCode(65+index)}) ${esc(option)}</button>`).join('')}</div>${taskActions()}<p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`;
  const errorTask = (item) => `<div class="task-card"><p class="prompt">„${esc(item.sentence)}“</p><div class="choices"><button data-choice="correcto">✅ Correcto</button><button data-choice="incorrecto">❌ Incorrecto</button></div>${taskActions()}<p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div><div id="explanation" class="explanation" hidden>${esc(item.explanation)}</div></div>`;
  const composeTask = (item) => `<div class="task-card"><p class="prompt">${esc(item.stem)} + <span class="blank">______</span></p><p class="small">${esc(item.person)} · -${item.group.toUpperCase()}-Verb</p><div class="answer-line"><input id="answer" class="answer-input" autocomplete="off" spellcheck="false" placeholder="Endung oder vollständige Form …"></div>${taskActions('<button type="button" id="check">Prüfen</button>')}<p id="feedback" class="feedback" aria-live="polite"></p><div id="hint" class="hint-box" hidden></div></div>`;
  function renderTask(items, title) { const item = items[state.index]; setProgress(title, state.index, items.length); const task = item.kind === 'input' ? inputTask(item) : item.kind === 'choice' ? choiceTask(item) : item.kind === 'error' ? errorTask(item) : composeTask(item); const modeTitle = ['level1','level3'].includes(state.screen) ? 'Konjugieren' : 'Im Kontext'; shell(title, `${modeTitle} · Aufgabe ${state.index+1}`, task); document.querySelector('[data-skip]')?.addEventListener('click', () => skipTask(item)); if (item.kind === 'input' || item.kind === 'compose' || item.kind === 'ending') { document.querySelector('#check').onclick = () => check(item, document.querySelector('#answer').value, (exhausted) => { if (exhausted) document.querySelector('#answer').disabled = true; }); document.querySelector('#answer').addEventListener('keydown', (event) => { if (event.key === 'Enter') document.querySelector('#check').click(); }); } else { document.querySelectorAll('[data-choice]').forEach(button => button.onclick = () => { const value = item.kind === 'error' ? button.dataset.choice : item.options[+button.dataset.choice]; check({...item, answer:item.kind === 'error' ? (item.answer === 'correcto' ? 'correcto' : 'incorrecto') : item.options[item.answer]}, value, () => { document.querySelectorAll('[data-choice]').forEach((b) => { b.disabled = true; }); document.querySelector('#explanation')?.removeAttribute('hidden'); }); }); } }
  function intro() { setProgress('Auswahl',0,1); shell('Pretérito imperfecto', 'Wähle deinen Lernbereich', `<p class="lead">Möchtest du zuerst regelmäßige Formen üben oder direkt mit den unregelmäßigen Verben <strong>ser, ir und ver</strong> starten?</p><div class="choice-grid"><article class="choice-card"><span class="choice-icon">📚</span><h2>Regelmäßige Verben</h2><p>Level 1: Formen bilden<br>Level 2: Im Kontext anwenden</p><button type="button" id="choose-regular">Regelmäßig starten →</button></article><article class="choice-card choice-card-special"><span class="choice-icon">⭐</span><h2>Unregelmäßige Verben</h2><p>Level 3: Formen von <strong>ser, ir, ver</strong><br>Level 4: Im Kontext anwenden</p><button type="button" id="choose-irregular">Unregelmäßig starten →</button></article></div><div class="panel"><p class="rule">ERKENNEN → BILDEN → ANWENDEN</p><p>Du kannst später jederzeit neu starten und den anderen Bereich wählen.</p></div>`); document.querySelector('#choose-regular').addEventListener('click', startLevel1); document.querySelector('#choose-irregular').addEventListener('click', startLevel3); }
  function startLevel1() { state.screen='level1'; state.index=0; state.score=0; state.attempts={}; renderTask(level1,'Level 1 · Formen bilden'); }
  function level1Done() { state.screen='level1done'; setProgress('Level 1 abgeschlossen',level1.length,level1.length); shell('✅ Level 1 abgeschlossen', 'Du kannst die Formen bilden.', `<div class="panel"><p class="lead">Stark! Jetzt brauchst du die Formen in kurzen Sätzen.</p><div class="level-map"><div class="level-node active">✅ Formen bilden</div><div class="level-arrow">↓</div><div class="level-node">⭐ Anwendung</div></div><p>Deine Fehler aus Level 1 werden in Level 2 gezielt wiederholt.</p></div>`, 'Weiter zu Level 2 – Anwendung →'); }
  function startLevel2() { state.screen='level2'; state.index=0; state.score=0; state.attempts={}; state.level2Items=level2Tasks(); renderTask(state.level2Items,'Level 2 · Anwendung im Kontext'); }
  function miniChallenge() { state.screen='challenge'; state.index=0; state.challengeScore=0; setProgress('Mini-Challenge',0,5); const items=[['De pequeño yo ___ mucho con mis amigos.','hablar','hablaba'],['Mi familia y yo ___ en una casa pequeña.','vivir','vivíamos'],['Todos los domingos nosotros ___ juntos.','comer','comíamos'],['Mis amigos ___ mucho deporte.','practicar','practicaban'],['En verano yo ___ a España.','viajar','viajaba']]; shell('🔥 MINI-CHALLENGE', 'Mi vida antes', `<p class="lead">Fünf kurze Sätze – diesmal ohne direkte Tipps.</p><div class="challenge-list">${items.map((item,index) => `<div class="challenge-row"><p>${index+1}. ${esc(item[0])}</p><small>(${esc(item[1])})</small><input class="answer-input" data-challenge="${index}" autocomplete="off" spellcheck="false" placeholder="Deine Lösung"></div>`).join('')}</div><p id="challenge-feedback" class="feedback"></p><div class="next-row"><button id="finish-challenge">Auswerten</button></div>`); document.querySelector('#finish-challenge').onclick = () => { state.challengeScore = items.reduce((sum,item,index) => sum + (normalize(document.querySelector(`[data-challenge="${index}"]`).value) === normalize(item[2]) ? 1 : 0),0); document.querySelectorAll('[data-challenge]').forEach(input => { input.disabled=true; }); document.querySelector('#finish-challenge').disabled=true; document.querySelector('#challenge-feedback').textContent=`${state.challengeScore} / 5`; setTimeout(regularComplete,500); }; }
  function regularComplete() { state.screen='regularcomplete'; setProgress('Regelmäßiger Bereich abgeschlossen',1,1); shell('✅ Regelmäßiger Bereich abgeschlossen', 'Jetzt kommen ser, ir und ver.', `<div class="panel"><p class="lead">Du kannst regelmäßige Imperfecto-Formen bilden und anwenden.</p><div class="level-map"><div class="level-node active">✅ Level 1–2<br><small>Regelmäßige Verben</small></div><div class="level-arrow">→</div><div class="level-node">⭐⭐⭐ Level 3–4<br><small>Unregelmäßige Verben</small></div></div><p>Die drei unregelmäßigen Verben lernst du jetzt zuerst als Formen und danach im Kontext.</p></div>`, 'Unregelmäßige Verben starten →'); }
  function startLevel3() { state.screen='level3'; state.index=0; state.score=0; state.attempts={}; renderTask(level3,'Level 3 · Unregelmäßige Formen'); }
  function level3Done() { state.screen='level3done'; setProgress('Level 3 abgeschlossen',level3.length,level3.length); shell('✅ Level 3 abgeschlossen', 'Die unregelmäßigen Formen sitzen.', `<div class="panel"><p class="lead">Sehr gut! Jetzt verwendest du <strong>ser, ir und ver</strong> in kurzen Sätzen.</p><p class="rule">ser · ir · ver → eigene Formen</p></div>`, 'Weiter zu Level 4 – Anwendung →'); }
  function startLevel4() { state.screen='level4'; state.index=0; state.score=0; state.attempts={}; state.level4Score=0; renderTask(level4,'Level 4 · Unregelmäßige Anwendung'); }
  function finish() { state.screen='finish'; setProgress('Abgeschlossen',1,1); const message='🎉 Du hast regelmäßige und unregelmäßige Verben angewendet.'; shell('Level 4 abgeschlossen', 'Pretérito imperfecto geschafft!', `<div class="finish"><h2>${message}</h2><p>Du hast den Weg von den Formen zur Anwendung geschafft.</p><p class="rule">ERKENNEN → BILDEN → ANWENDEN</p></div>`, 'Noch einmal starten'); }
  function next() { if(state.screen==='intro') return startLevel1(); if(state.screen==='level1') { if(state.index < level1.length-1) { state.index += 1; return renderTask(level1,'Level 1 · Formen bilden'); } return level1Done(); } if(state.screen==='level1done') return startLevel2(); if(state.screen==='level2') { if(state.index < state.level2Items.length-1) { state.index += 1; return renderTask(state.level2Items,'Level 2 · Anwendung im Kontext'); } return miniChallenge(); } if(state.screen==='challenge') return regularComplete(); if(state.screen==='regularcomplete') return startLevel3(); if(state.screen==='level3') { if(state.index < level3.length-1) { state.index += 1; return renderTask(level3,'Level 3 · Unregelmäßige Formen'); } return level3Done(); } if(state.screen==='level3done') return startLevel4(); if(state.screen==='level4') { if(state.index < level4.length-1) { state.index += 1; return renderTask(level4,'Level 4 · Unregelmäßige Anwendung'); } return finish(); } if(state.screen==='finish') { state.screen='intro'; state.index=0; state.score=0; state.challengeScore=0; return intro(); } }
  state.mistakes = saved.mistakes || {}; intro();
})();
