(() => {
  const $ = selector => document.querySelector(selector);
  const state = { data: null, lesson: 0, task: 0, xp: Number(localStorage.getItem('linguacode-java-xp') || 0), completed: new Set(JSON.parse(localStorage.getItem('linguacode-java-completed') || '[]')), hints: 0, teacher: false };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const api = path => `${window.LINGUACODE_JAVA_API || window.location.origin}/api/java/${path}`;
  const allTasks = () => state.data.lessons.flatMap(lesson => lesson.tasks);
  const current = () => state.data.lessons[state.lesson].tasks[state.task];
  const persist = () => { localStorage.setItem('linguacode-java-xp', String(state.xp)); localStorage.setItem('linguacode-java-completed', JSON.stringify([...state.completed])); $('#xp').textContent = `${state.xp} XP`; };
  const lines = editor => { $('#line-numbers').textContent = Array.from({length: editor.value.split('\n').length}, (_, i) => i + 1).join('\n'); };
  const showFeedback = (kind, title, detail = '') => { const box = $('#feedback'); if (!box) return; box.className = `feedback ${kind}`; box.innerHTML = `<strong>${esc(title)}</strong>${detail ? `<small>${esc(detail)}</small>` : ''}`; };
  const markComplete = task => { if (!state.completed.has(task.id)) { state.completed.add(task.id); state.xp += Math.max(0, 100 - state.hints * 25); persist(); } updateProgress(); };
  const updateProgress = () => { const percent = Math.round(state.completed.size / allTasks().length * 100); $('#progress-text').textContent = `${percent} %`; $('#progress-bar').style.width = `${percent}%`; $('#mastered').innerHTML = [...state.completed].slice(-4).map(id => `<li>${esc(id)}</li>`).join(''); };
  const nextButton = () => `<button class="primary next" id="next">Weiter →</button>`;
  const renderLessons = () => { $('#lessons').innerHTML = state.data.lessons.map((lesson, i) => `<button class="lesson-button ${i === state.lesson ? 'active' : ''}" data-lesson="${i}"><strong>${String(i + 1).padStart(2, '0')} ${esc(lesson.title)}</strong><small>${lesson.tasks.filter(task => state.completed.has(task.id)).length}/${lesson.tasks.length} abgeschlossen</small></button>`).join(''); document.querySelectorAll('[data-lesson]').forEach(button => button.onclick = () => { state.lesson = Number(button.dataset.lesson); state.task = 0; render(); }); };
  const render = () => { const lesson = state.data.lessons[state.lesson]; $('#lesson-intro').innerHTML = `<p class="task-kicker">Lesson ${esc(lesson.id)}</p><h2>${esc(lesson.title)}</h2><p>${esc(lesson.goal)}</p>`; renderLessons(); renderTask(); updateProgress(); };
  const renderTask = () => { state.hints = 0; const task = current(); const card = $('#task-card'); card.innerHTML = `<span class="task-kicker">Aufgabe ${state.task + 1} / ${state.data.lessons[state.lesson].tasks.length}</span><h2>${esc(task.title)}</h2><p class="instruction">${esc(task.instruction)}</p>${state.teacher ? `<aside class="teacher-note teacher-only"><strong>Teacher Note</strong><p>Arbeitsziel: ${esc(state.data.lessons[state.lesson].goal)}</p></aside>` : ''}${task.type === 'predict' ? predict(task) : task.type === 'completion' ? completion(task) : task.type === 'text' ? textTask(task) : codeTask(task)}`; bindTask(task); };
  const predict = task => `<pre class="console-output">${esc(task.code)}</pre><div class="choices">${task.options.map((option, i) => `<button class="choice" data-choice="${i}">${esc(option)}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div>`;
  const completion = task => `<input class="completion-input" id="answer" autocomplete="off" aria-label="Antwort" placeholder="Deine Ergänzung"><div class="answer-actions"><button class="primary" id="check-answer">✓ CHECK</button><button class="hint-button" id="hint">💡 HINT</button></div><div id="feedback" aria-live="polite"></div><div id="hint-panel"></div>`;
  const textTask = task => `<pre class="console-output">${esc(task.code)}</pre><input class="text-answer" id="answer" autocomplete="off" aria-label="Antwort" placeholder="Deine Antwort"><div class="answer-actions"><button class="primary" id="check-answer">✓ CHECK</button></div><div id="feedback" aria-live="polite"></div>`;
  const codeTask = task => `<div class="code-layout"><div><div class="editor-shell"><div class="editor-bar"><span>Main.java</span><span>⌘/Ctrl + Enter · RUN</span></div><div class="editor-wrap"><pre class="line-numbers" id="line-numbers">1</pre><textarea class="code-editor" id="editor" spellcheck="false" aria-label="Java-Codeeditor">${esc(task.starterCode || '')}</textarea></div></div><div class="toolbar"><button class="primary" id="run">▶ RUN</button><button class="primary" id="check">✓ CHECK</button><button class="secondary" id="reset">↻ RESET</button><button class="hint-button" id="hint">💡 HINT</button></div></div><div class="console"><div class="console-bar"><span>CONSOLE</span><span id="runner-state">Ready</span></div><div class="console-output" id="console-output" aria-live="polite">&gt; Ready</div></div></div><div id="feedback" aria-live="polite"></div><div id="hint-panel"></div>`;
  const bindTask = task => {
    const editor = $('#editor');
    if (editor) { lines(editor); editor.addEventListener('input', () => lines(editor)); editor.addEventListener('keydown', event => { if (event.key === 'Tab') { event.preventDefault(); const start = editor.selectionStart; editor.setRangeText('  ', start, editor.selectionEnd, 'end'); lines(editor); } if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') { event.preventDefault(); $('#run').click(); } if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key === 'Enter') { event.preventDefault(); $('#check').click(); } }); }
    $('#hint')?.addEventListener('click', () => { state.hints = Math.min(state.hints + 1, (task.hints || []).length); $('#hint-panel').innerHTML = state.hints ? `<div class="hint-panel"><strong>Hint ${state.hints}</strong><p>${esc(task.hints[state.hints - 1])}</p>${state.hints >= (task.hints || []).length ? `<button class="secondary" id="reveal">Lösung anzeigen</button>` : ''}</div>` : ''; $('#reveal')?.addEventListener('click', () => { $('#hint-panel').innerHTML += `<div class="solution"><strong>Musterlösung</strong><pre><code>${esc(task.solution || '')}</code></pre></div>`; }); });
    $('#reset')?.addEventListener('click', () => { editor.value = task.starterCode || ''; lines(editor); $('#console-output').textContent = '> Ready'; $('#runner-state').textContent = 'Ready'; $('#feedback').innerHTML = ''; });
    $('#run')?.addEventListener('click', () => run(task, false));
    $('#check')?.addEventListener('click', () => run(task, true));
    $('#check-answer')?.addEventListener('click', () => { const answer = $('#answer').value.trim(); const expected = String(task.expected || task.answerText || '').trim(); const ok = answer.toLowerCase() === expected.toLowerCase(); if (ok) { markComplete(task); showFeedback('success', '✓ Richtig!', task.explanation || ''); $('#task-card').insertAdjacentHTML('beforeend', nextButton()); $('#next').onclick = advance; } else showFeedback('warning', '⚠ Fast geschafft.', 'Prüfe deine Antwort noch einmal.'); });
    document.querySelectorAll('[data-choice]').forEach(button => button.onclick = () => { const ok = Number(button.dataset.choice) === task.answer; document.querySelectorAll('[data-choice]').forEach(item => item.disabled = true); button.classList.add(ok ? 'correct' : 'wrong'); if (ok) { markComplete(task); showFeedback('success', '✓ Richtig!', task.explanation); $('#task-card').insertAdjacentHTML('beforeend', nextButton()); $('#next').onclick = advance; } else showFeedback('error', 'Noch nicht.', 'Lies den Code Zeile für Zeile.'); });
  };
  const run = async (task, check) => { const output = $('#console-output'); const stateLabel = $('#runner-state'); const code = $('#editor').value; output.textContent = check ? 'Checking...' : 'Running...'; stateLabel.textContent = check ? 'Checking...' : 'Running...'; $('#run').disabled = $('#check').disabled = true; try { const response = await fetch(api(check ? 'check' : 'run'), {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({code, taskId:task.id, lessonId:state.data.lessons[state.lesson].id})}); const result = await response.json(); output.textContent = result.stdout || result.stderr || `> ${result.message || 'Keine Ausgabe'}`; output.className = `console-output ${result.success ? 'success' : 'error'}`; stateLabel.textContent = result.success ? 'Finished' : 'Error'; if (result.success && check) { markComplete(task); showFeedback('success', result.feedback?.title || '✓ Richtig!', result.feedback?.detail || ''); $('#task-card').insertAdjacentHTML('beforeend', nextButton()); $('#next').onclick = advance; } else if (!result.success) showFeedback(result.status === 'compile-error' ? 'error' : 'warning', result.feedback?.title || 'Java kann deinen Code noch nicht kompilieren.', result.feedback?.detail || result.stderr || result.message || ''); } catch (error) { output.textContent = '> Runner nicht erreichbar'; stateLabel.textContent = 'Offline'; showFeedback('warning', 'Java-Runner nicht erreichbar.', 'Die Oberfläche ist bereit; der sichere Docker-Runner muss auf dem PHP-Server aktiviert werden.'); } finally { $('#run').disabled = $('#check').disabled = false; } };
  const advance = () => { if (state.task < state.data.lessons[state.lesson].tasks.length - 1) state.task++; else if (state.lesson < state.data.lessons.length - 1) { state.lesson++; state.task = 0; } else { showFeedback('success', '🎓 Java Lab abgeschlossen!', 'Baue jetzt dein eigenes Programm.'); return; } render(); };
  $('#presentation')?.addEventListener('click', () => document.body.classList.toggle('presentation'));
  $('#mode')?.addEventListener('click', () => { state.teacher = !state.teacher; document.body.classList.toggle('teacher-mode', state.teacher); $('#mode').textContent = state.teacher ? 'Teacher' : 'Student'; renderTask(); });
  fetch('tasks.json').then(response => response.json()).then(data => { state.data = data; persist(); render(); }).catch(() => { $('#task-card').textContent = 'Die Aufgaben konnten nicht geladen werden.'; });
})();
