(() => {
'use strict';
const SIZE=8, KEY='linguacode-kara-sandbox-v2';
const sensors=['kein Baum vorne','Baum vorne','Kleeblatt unter Kara','keine passende Eingabe'];
const actions=['vorwärts gehen','nach links drehen','nach rechts drehen','Kleeblatt aufnehmen','Kleeblatt ablegen'];
const $=s=>document.querySelector(s), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const S={world:null,states:[],transitions:[],current:'q0',selectedTool:'kara',running:false,timer:null,selectedState:null};
function defaultMachine(){S.world={x:1,y:6,dir:1,trees:[[4,3]],clovers:[[6,2]],collected:0};S.states=[{id:'q0',x:12,y:28,start:true,end:false},{id:'q1',x:46,y:28,start:false,end:true}];S.transitions=[{from:'q0',to:'q1',sensor:'kein Baum vorne',action:'vorwärts gehen'}];S.current='q0';}
function save(){try{localStorage.setItem(KEY,JSON.stringify({world:S.world,states:S.states,transitions:S.transitions,current:S.current}));$('#save-state').textContent='Gespeichert';}catch(_){$('#save-state').textContent='Nur diese Sitzung';}}
function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return false;const data=JSON.parse(raw);if(!data.world||!Array.isArray(data.states)||!Array.isArray(data.transitions))return false;Object.assign(S,data);S.running=false;return true;}catch(_){return false;}}
function direction(){return [[0,-1],[1,0],[0,1],[-1,0]][S.world.dir];} function at(list,x,y){return list.some(p=>p[0]===x&&p[1]===y);}
function renderWorld(){const world=$('#world');world.innerHTML='';for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const cell=document.createElement('button');cell.type='button';cell.className='cell';cell.dataset.x=x;cell.dataset.y=y;if(at(S.world.trees,x,y)){cell.classList.add('tree');cell.textContent='🌳';}if(at(S.world.clovers,x,y)){cell.classList.add('clover');cell.textContent='☘️';}if(S.world.x===x&&S.world.y===y){const kara=document.createElement('span');kara.className=`kara ${['north','east','south','west'][S.world.dir]}`;kara.textContent='🐞';cell.append(kara);}cell.onclick=()=>editCell(x,y);world.append(cell);}}
function editCell(x,y){if(S.selectedTool==='kara'){S.world.x=x;S.world.y=y;}if(S.selectedTool==='turn'&&S.world.x===x&&S.world.y===y)S.world.dir=(S.world.dir+1)%4;if(S.selectedTool==='tree'){const i=S.world.trees.findIndex(p=>p[0]===x&&p[1]===y);i<0?S.world.trees.push([x,y]):S.world.trees.splice(i,1);}if(S.selectedTool==='clover'){const i=S.world.clovers.findIndex(p=>p[0]===x&&p[1]===y);i<0?S.world.clovers.push([x,y]):S.world.clovers.splice(i,1);}if(S.selectedTool==='erase'){S.world.trees=S.world.trees.filter(p=>p[0]!==x||p[1]!==y);S.world.clovers=S.world.clovers.filter(p=>p[0]!==x||p[1]!==y);}save();renderWorld();}
function sensor(){const[dx,dy]=direction(),nx=S.world.x+dx,ny=S.world.y+dy;if(at(S.world.trees,nx,ny))return'Baum vorne';if(at(S.world.clovers,S.world.x,S.world.y))return'Kleeblatt unter Kara';return'kein Baum vorne';}
function doAction(a){if(a==='vorwärts gehen'){const[dx,dy]=direction(),nx=S.world.x+dx,ny=S.world.y+dy;if(nx<0||ny<0||nx>=SIZE||ny>=SIZE||at(S.world.trees,nx,ny))return false;S.world.x=nx;S.world.y=ny;}if(a==='nach links drehen')S.world.dir=(S.world.dir+3)%4;if(a==='nach rechts drehen')S.world.dir=(S.world.dir+1)%4;if(a==='Kleeblatt aufnehmen'){const i=S.world.clovers.findIndex(p=>p[0]===S.world.x&&p[1]===S.world.y);if(i<0)return false;S.world.clovers.splice(i,1);S.world.collected++;}if(a==='Kleeblatt ablegen'){if(at(S.world.clovers,S.world.x,S.world.y))return false;S.world.clovers.push([S.world.x,S.world.y]);}return true;}
function select(values,chosen,attrs){return`<select ${attrs}>${values.map(v=>`<option value="${esc(v)}" ${v===chosen?'selected':''}>${esc(v)}</option>`).join('')}</select>`;}
function renderProgram(){$('#program').innerHTML=S.states.map(st=>`<article class="state-card ${st.id===S.current?'active':''}"><div class="state-title"><button class="state-link" data-select-state="${esc(st.id)}">${esc(st.id)} ${st.start?'· Start':''} ${st.end?'· Ziel':''}</button><button class="small-button" data-toggle-start="${esc(st.id)}">${st.start?'Start entfernen':'Als Start markieren'}</button><button class="small-button" data-toggle-end="${esc(st.id)}">${st.end?'Ziel entfernen':'Als Ziel markieren'}</button></div>${S.transitions.filter(t=>t.from===st.id).map(t=>{const i=S.transitions.indexOf(t);return`<div class="rule"><span>Wenn</span>${select(sensors,t.sensor,`data-transition="${i}" data-field="sensor"`)}<span>→</span>${select(actions,t.action,`data-transition="${i}" data-field="action"`)}${select(S.states.map(s=>s.id),t.to,`data-transition="${i}" data-field="to"`)}<button class="icon-button" title="Übergang löschen" data-remove-transition="${i}">×</button></div>`;}).join('')}<button class="small-button add-rule" data-add-transition="${esc(st.id)}">+ Übergang</button></article>`).join('');$('#program').querySelectorAll('[data-transition]').forEach(el=>el.onchange=()=>{const t=S.transitions[+el.dataset.transition];t[el.dataset.field]=el.value;save();renderAll();});$('#program').querySelectorAll('[data-remove-transition]').forEach(b=>b.onclick=()=>{S.transitions.splice(+b.dataset.removeTransition,1);save();renderAll();});$('#program').querySelectorAll('[data-add-transition]').forEach(b=>b.onclick=()=>{S.transitions.push({from:b.dataset.addTransition,to:S.states[0].id,sensor:'kein Baum vorne',action:'vorwärts gehen'});save();renderAll();});$('#program').querySelectorAll('[data-toggle-start]').forEach(b=>b.onclick=()=>{S.states.forEach(s=>s.start=false);S.states.find(s=>s.id===b.dataset.toggleStart).start=true;S.current=b.dataset.toggleStart;save();renderAll();});$('#program').querySelectorAll('[data-toggle-end]').forEach(b=>b.onclick=()=>{const s=S.states.find(x=>x.id===b.dataset.toggleEnd);s.end=!s.end;save();renderAll();});$('#program').querySelectorAll('[data-select-state]').forEach(b=>b.onclick=()=>{S.selectedState=b.dataset.selectState;renderEditor();});}
function renderDiagram(){const d=$('#diagram');d.innerHTML=S.states.map(s=>`<div class="diagram-node-wrap" style="left:${s.x}%;top:${s.y}%"><button class="node ${s.id===S.current?'active':''} ${s.start?'start':''} ${s.end?'end':''}" draggable="true" data-node="${esc(s.id)}">${esc(s.id)}<span class="port" draggable="true" data-port="${esc(s.id)}">↗</span></button><button class="node-menu" data-edit-state="${esc(s.id)}">⚙</button></div>`).join('');d.querySelectorAll('[data-node]').forEach(n=>{n.ondragstart=e=>e.dataTransfer.setData('text/plain',n.dataset.node);n.ondragend=e=>{const st=S.states.find(x=>x.id===n.dataset.node),r=d.getBoundingClientRect();st.x=Math.max(4,Math.min(92,(e.clientX-r.left)/r.width*100));st.y=Math.max(10,Math.min(88,(e.clientY-r.top)/r.height*100));save();renderDiagram();};n.onclick=()=>{S.selectedState=n.dataset.node;renderEditor();};});d.querySelectorAll('[data-port]').forEach(p=>p.ondragstart=e=>{e.stopPropagation();e.dataTransfer.setData('text/kara-from',p.dataset.port);});d.querySelectorAll('[data-edit-state]').forEach(b=>b.onclick=()=>{S.selectedState=b.dataset.editState;renderEditor();});d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=e.dataTransfer.getData('text/kara-from'),to=e.target.closest('[data-node]')?.dataset.node;if(from&&to&&from!==to){S.transitions.push({from,to,sensor:'kein Baum vorne',action:'vorwärts gehen'});save();renderAll();}};renderEditor();}
function renderEditor(){const st=S.states.find(s=>s.id===S.selectedState);if(!st){$('#diagram-editor').innerHTML='<p class="muted">Klicke auf ⚙ an einem Zustand, um ihn umzubenennen oder zu löschen.</p>';return;}$('#diagram-editor').innerHTML=`<div class="editor-card"><b>Zustand bearbeiten</b><label>Name <input id="state-name" value="${esc(st.id)}" maxlength="12"></label><button id="rename-state">Umbenennen</button><button id="delete-state" class="danger">Zustand löschen</button></div>`;$('#rename-state').onclick=()=>{const next=$('#state-name').value.trim();if(!next||S.states.some(s=>s.id===next&&s!==st))return;const old=st.id;st.id=next;S.transitions.forEach(t=>{if(t.from===old)t.from=next;if(t.to===old)t.to=next;});if(S.current===old)S.current=next;S.selectedState=next;save();renderAll();};$('#delete-state').onclick=()=>{if(S.states.length<=1)return;S.states=S.states.filter(s=>s!==st);S.transitions=S.transitions.filter(t=>t.from!==st.id&&t.to!==st.id);if(S.current===st.id)S.current=S.states[0].id;S.selectedState=null;save();renderAll();};}
function renderBlocks(){$('#blocks').innerHTML=actions.map(a=>`<button class="block" draggable="true" data-action="${esc(a)}">${esc(a)}</button>`).join('');$('#blocks').querySelectorAll('[data-action]').forEach(b=>{b.onclick=()=>{const t=S.transitions.find(x=>x.from===S.current)||S.transitions[0];if(t){t.action=b.dataset.action;save();renderAll();}};});}
function renderAll(){renderWorld();renderProgram();renderDiagram();renderBlocks();$('#state-label').textContent=`Zustand: ${S.current}`;}
function stop(msg){S.running=false;clearTimeout(S.timer);$('#run-state').textContent='Fehler';$('#feedback').textContent=msg;$('#feedback').classList.add('bad');}
function step(){const input=sensor(),t=S.transitions.find(x=>x.from===S.current&&(x.sensor===input||x.sensor==='keine passende Eingabe'));if(!t){stop(`Kein Übergang für „${input}“.`);return false;}if(!doAction(t.action)){stop('Aktion nicht möglich: Kara würde mit einem Baum kollidieren oder kann hier kein Kleeblatt aufnehmen.');return false;}S.current=t.to;$('#transition-label').textContent=`${input} → ${t.action} → ${S.current}`;$('#feedback').textContent='';$('#feedback').classList.remove('bad');save();renderAll();return true;}
function run(){if(S.running)return;S.running=true;$('#run-state').textContent='Läuft';const tick=()=>{if(!S.running)return;if(step())S.timer=setTimeout(tick,550);};tick();}
function reset(){defaultMachine();save();$('#run-state').textContent='Bereit';$('#feedback').textContent='';renderAll();}
function check(){const ok=S.states.some(s=>s.start)&&S.states.some(s=>s.end)&&S.transitions.length>0;$('#feedback').classList.toggle('bad',!ok);$('#feedback').textContent=ok?'Gut! Dein Automat hat Start, Ziel und mindestens einen Übergang. Teste ihn weiter.':'Noch nicht: Markiere einen Start- und einen Zielzustand und zeichne mindestens einen Übergang.';}
function init(){defaultMachine();$('#start-button').onclick=()=>{$('#intro').hidden=true;$('#game').hidden=false;renderAll();};$('#restore-button').onclick=()=>{if(load()){$('#intro').hidden=true;$('#game').hidden=false;renderAll();}else $('#save-state').textContent='Noch kein Speicherstand';};$('#world-tools').querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{$('#world-tools .selected').classList.remove('selected');b.classList.add('selected');S.selectedTool=b.dataset.tool;});$('#run').onclick=run;$('#pause').onclick=()=>{S.running=false;clearTimeout(S.timer);$('#run-state').textContent='Pausiert';};$('#step').onclick=()=>{S.running=false;$('#run-state').textContent='Schrittmodus';step();};$('#reset').onclick=reset;$('#check').onclick=check;$('#add-state').onclick=()=>{const n=S.states.length;S.states.push({id:`q${n}`,x:20+(n*13)%65,y:60+(n*11)%25,start:false,end:false});save();renderAll();};$('#clear-machine').onclick=()=>{S.transitions=[];S.states.forEach(s=>{s.start=false;s.end=false;});save();renderAll();};}
init();
})();
