(() => {
  'use strict';
  const SIZE = 8;
  const missions = [
    {title:'Mission 1: Kara startet', explanation:'Kara soll zwei Felder nach vorne gehen. Jeder Schritt ist ein Übergang: Kara ist vorher in einem Zustand und danach in einem neuen Zustand.', world:{kara:[3,6,1],clovers:[],trees:[]}, goal:'reach', goalText:'Kara erreicht das Zielfeld.'},
    {title:'Mission 2: Die Richtung ändern', explanation:'Kara schaut zunächst in die falsche Richtung. Drehe Kara nach rechts und gehe dann zum Kleeblatt.', world:{kara:[2,6,1],clovers:[[2,4]],trees:[]}, goal:'clover', goalText:'Kara erreicht das Kleeblatt.'},
    {title:'Mission 3: Der Baum im Weg', explanation:'Ein Baum blockiert den Weg. Ein Sensor liefert die Eingabe „Baum vorne?“. Kara darf nicht in den Baum laufen, sondern muss abbiegen.', world:{kara:[2,6,1],clovers:[[4,4]],trees:[[2,4],[3,4]]}, goal:'clover', goalText:'Kara erreicht das Kleeblatt ohne Kollision.'},
    {title:'Mission 4: Kleeblätter sammeln', explanation:'Kara soll mehrere Kleeblätter sammeln. Wenn Kara ein Kleeblatt erkennt, führt der Automat die Aktion „aufnehmen“ aus.', world:{kara:[1,6,1],clovers:[[1,4],[4,4]],trees:[[2,5]]}, goal:'collect', goalText:'Alle Kleeblätter sind eingesammelt.'},
    {title:'Mission 5: Eigenen Automaten bauen', explanation:'Jetzt bist du dran: Erstelle mindestens vier Zustände, vier Übergänge, einen Startzustand und einen Endzustand. Teste deinen Automaten Schritt für Schritt.', world:{kara:[3,6,1],clovers:[[3,2]],trees:[[2,4]]}, goal:'custom', goalText:'Dein eigener Automat erfüllt die Mindestbedingungen.'}
  ];
  const labels={forward:'vorwärts gehen',left:'nach links drehen',right:'nach rechts drehen',pick:'Kleeblatt aufnehmen',drop:'Kleeblatt ablegen'};
  const sensors=['kein Baum vorne','Baum vorne','Kleeblatt unter Kara','keine passende Eingabe'];
  const S={mission:0,stars:0,states:[],transitions:[],world:null,queue:[],running:false};
  const $=s=>document.querySelector(s), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function fresh(){const m=missions[S.mission];S.world={x:m.world.kara[0],y:m.world.kara[1],dir:m.world.kara[2],clovers:m.world.clovers.map(p=>[...p]),trees:m.world.trees.map(p=>[...p]),collected:0};S.states=[{id:'q0',start:true,end:false},{id:'q1',start:false,end:S.mission===0}];S.transitions=[{from:'q0',to:'q1',sensor:'kein Baum vorne',action:'vorwärts gehen'}];S.queue=[];S.running=false;save();}
  function currentDir(){return [[0,-1],[1,0],[0,1],[-1,0]][S.world.dir]}
  function renderWorld(){const w=$('#world');w.innerHTML='';for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const c=document.createElement('div');c.className='cell';const tree=S.world.trees.some(p=>p[0]===x&&p[1]===y),clover=S.world.clovers.some(p=>p[0]===x&&p[1]===y);if(tree)c.classList.add('tree');if(clover)c.classList.add('clover');c.textContent=tree?'🌳':clover?'☘️':'';if(S.world.x===x&&S.world.y===y){const k=document.createElement('span');k.className=`kara ${['north','east','south','west'][S.world.dir]}`;k.textContent='🐞';c.append(k)};w.append(c)}}
  function state(id){return S.states.find(s=>s.id===id)||S.states[0]}
  function renderProgram(){const p=$('#program');p.innerHTML=S.states.map(st=>`<article class="state-card ${st.id===S.queue[0]?.from?'active':''}"><div class="state-title"><span>${esc(st.id)} ${st.start?'· Start':''} ${st.end?'· Ziel':''}</span><button class="small-button" data-toggle-end="${st.id}">${st.end?'Ziel entfernen':'Als Ziel markieren'}</button></div>${S.transitions.map((t,i)=>t.from===st.id?`<div class="rule"><span>wenn</span><select data-transition="${i}" data-field="sensor">${sensors.map(x=>`<option ${x===t.sensor?'selected':''}>${x}</option>`).join('')}</select><span>→</span><select data-transition="${i}" data-field="action">${Object.values(labels).map(x=>`<option ${x===t.action?'selected':''}>${x}</option>`).join('')}</select><select data-transition="${i}" data-field="to">${S.states.map(x=>`<option ${x.id===t.to?'selected':''}>${x.id}</option>`).join('')}</select></div>`:'').join('')}<button class="small-button" data-add-transition="${st.id}">+ Übergang erklären</button></article>`).join('');p.querySelectorAll('[data-toggle-end]').forEach(b=>b.onclick=()=>{state(b.dataset.toggleEnd).end=!state(b.dataset.toggleEnd).end;renderAll()});p.querySelectorAll('select[data-transition]').forEach(s=>s.onchange=()=>{const t=S.transitions[+s.dataset.transition];t[s.dataset.field]=s.value;save();renderAll()});p.querySelectorAll('[data-add-transition]').forEach(b=>b.onclick=()=>{S.transitions.push({from:b.dataset.addTransition,to:S.states[0].id,sensor:'kein Baum vorne',action:'vorwärts gehen'});save();renderAll()})}
  function renderDiagram(){const d=$('#diagram');d.innerHTML=S.states.map((s,i)=>`${i?' <span class="arrow">→</span>':''}<span class="node ${s.id===S.queue[0]?.from?'active':''}" title="${s.start?'Startzustand':''}">${s.id}</span>`).join('');$('#diagram-editor').innerHTML=S.transitions.map((t,i)=>`<div class="transition-row"><b>${t.from}</b> → <span>${esc(t.sensor)} / ${esc(t.action)}</span> → <b>${t.to}</b><button data-remove="${i}">×</button></div>`).join('');$('#diagram-editor').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{S.transitions.splice(+b.dataset.remove,1);renderAll()})}
  function renderBlocks(){$('#blocks').innerHTML=Object.entries(labels).map(([key,label])=>`<button class="block" data-action="${esc(label)}">${esc(label)}</button>`).join('');$('#blocks').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const t=S.transitions[0]||{from:'q0',to:'q1',sensor:'kein Baum vorne',action:b.dataset.action};t.action=b.dataset.action;if(!S.transitions.length)S.transitions.push(t);renderAll()})}
  function renderAll(){renderWorld();renderProgram();renderDiagram();renderBlocks();$('#state-label').textContent=`Zustand: ${S.queue[0]?.from||'q0'}`;$('#mission-count').textContent=`Mission ${S.mission+1} von 5`;$('#stars').textContent=S.stars}
  function sensor(){const [dx,dy]=currentDir(),nx=S.world.x+dx,ny=S.world.y+dy;return S.world.trees.some(p=>p[0]===nx&&p[1]===ny)?'Baum vorne':S.world.clovers.some(p=>p[0]===S.world.x&&p[1]===S.world.y)?'Kleeblatt unter Kara':'kein Baum vorne'}
  function action(a){if(a==='vorwärts gehen'){const [dx,dy]=currentDir(),nx=S.world.x+dx,ny=S.world.y+dy;if(nx<0||ny<0||nx>=SIZE||ny>=SIZE||S.world.trees.some(p=>p[0]===nx&&p[1]===ny))return false;S.world.x=nx;S.world.y=ny}if(a==='nach links drehen')S.world.dir=(S.world.dir+3)%4;if(a==='nach rechts drehen')S.world.dir=(S.world.dir+1)%4;if(a==='Kleeblatt aufnehmen'){const i=S.world.clovers.findIndex(p=>p[0]===S.world.x&&p[1]===S.world.y);if(i>=0){S.world.clovers.splice(i,1);S.world.collected++}}if(a==='Kleeblatt ablegen')S.world.clovers.push([S.world.x,S.world.y]);return true}
  function step(){const current=S.queue.length?S.queue[0]:{from:S.states.find(s=>s.start)?.id||'q0'};const input=sensor();const t=S.transitions.find(x=>x.from===current.from&&(x.sensor===input||x.sensor==='keine passende Eingabe'));if(!t){$('#feedback').textContent='Kara hat keinen Übergang für diese Situation.';$('#feedback').classList.add('bad');S.running=false;$('#run-state').textContent='Fehler';return}if(!action(t.action)){ $('#feedback').textContent='Kara steht vor einem Baum. Für diese Eingabe fehlt ein passender Übergang.';$('#feedback').classList.add('bad');S.running=false;return}S.queue=[{from:t.to}];$('#transition-label').textContent=`Eingabe: ${input} · Aktion: ${t.action} · Nächster Zustand: ${t.to}`;$('#feedback').textContent='';$('#feedback').classList.remove('bad');renderAll();if(S.running)setTimeout(step,450)}
  function check(){const m=missions[S.mission],valid=S.states.length>=(S.mission===4?4:2)&&S.transitions.length>=(S.mission===4?4:1)&&S.states.some(s=>s.start)&&S.states.some(s=>s.end);const goal=m.goal==='collect'?S.world.collected>=2:m.goal==='custom'?valid:(m.goal==='clover'?S.world.clovers.length===0:(S.world.x!==m.world.kara[0]||S.world.y!==m.world.kara[1]));if(valid&&goal){S.stars=Math.max(S.stars,S.mission+1);save();$('#feedback').textContent='Geschafft! Kara hat den richtigen Zustandsweg gefunden.';setTimeout(()=>showMissionEnd(),250)}else{$('#feedback').textContent=m.goal==='custom'?'Baue mindestens vier Zustände, vier Übergänge sowie einen Start- und einen Endzustand.':'Noch nicht. Teste deinen Automaten Schritt für Schritt.';$('#feedback').classList.add('bad')}}
  function showMissionEnd(){const d=$('#mission-dialog');$('#dialog-content').innerHTML=`<h2>${missions[S.mission].title} geschafft!</h2><p>${missions[S.mission].goalText}</p><p>Du erhältst ⭐ ${S.mission+1}.</p>`;d.showModal()}
  function save(){try{localStorage.setItem('linguacode-kara-progress',JSON.stringify({mission:S.mission,stars:S.stars}))}catch{}}
  function next(){if(S.mission<missions.length-1){S.mission++;fresh();renderAll();$('#mission-explanation').textContent=missions[S.mission].explanation;$('#feedback').textContent=''}else{$('#mission-explanation').textContent='Alle fünf Missionen sind abgeschlossen. Stark programmiert!';$('#feedback').textContent='🎉 Kara-Profi!';save()}}
  $('#start-button').onclick=()=>{$('#intro').hidden=true;$('#game').hidden=false;fresh();$('#mission-explanation').textContent=missions[0].explanation;renderAll()};$('#run').onclick=()=>{S.running=true;$('#run-state').textContent='Läuft';step()};$('#step').onclick=()=>{S.running=false;$('#run-state').textContent='Schrittmodus';step()};$('#pause').onclick=()=>{S.running=false;$('#run-state').textContent='Pausiert'};$('#reset').onclick=()=>{fresh();renderAll();$('#run-state').textContent='Bereit'};$('#check').onclick=check;$('#dialog-close').onclick=()=>{$('#mission-dialog').close();next()};$('#add-state').onclick=()=>{S.states.push({id:`q${S.states.length}`,start:false,end:false});renderAll()};
})();
