(() => {
'use strict';
const SIZE=8, KEY='linguacode-kara-sandbox-v2';
const sensors=['kein Baum vorne','Baum vorne','Kleeblatt unter Kara','keine passende Eingabe'];
const actions=['vorwärts gehen','nach links drehen','nach rechts drehen','Kleeblatt aufnehmen','Kleeblatt ablegen'];
const $=s=>document.querySelector(s), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const S={world:null,states:[],transitions:[],current:'q0',selectedTool:'kara',running:false,timer:null,selectedState:'q0',selectedTransition:null,drag:null};
const uid=(prefix,list)=>{let n=list.length;while(list.some(x=>x.id===prefix+n))n++;return prefix+n;};
function defaultMachine(){S.world={x:1,y:6,dir:1,trees:[[4,3]],clovers:[[6,2]],collected:0};S.states=[{id:'q0',label:'q0',x:22,y:50,start:true,end:false},{id:'q1',label:'q1',x:70,y:50,start:false,end:true}];S.transitions=[{id:'t0',from:'q0',to:'q1',sensor:'kein Baum vorne',action:'vorwärts gehen'}];S.current='q0';S.selectedState='q0';S.selectedTransition=null;}
function normalize(data){S.world=data.world;S.states=(data.states||[]).map((s,i)=>({id:s.id||'q'+i,label:s.label||s.id||'q'+i,x:Number.isFinite(+s.x)?+s.x:20+i*20,y:Number.isFinite(+s.y)?+s.y:50,start:!!s.start,end:!!s.end}));S.transitions=(data.transitions||[]).map((t,i)=>({id:t.id||'t'+i,from:t.from,to:t.to,sensor:sensors.includes(t.sensor)?t.sensor:sensors[0],action:actions.includes(t.action)?t.action:actions[0]})).filter(t=>S.states.some(s=>s.id===t.from)&&S.states.some(s=>s.id===t.to));S.current=S.states.some(s=>s.id===data.current)?data.current:(S.states.find(s=>s.start)||S.states[0]?.id||'q0');S.selectedState=S.current;S.selectedTransition=null;}
function save(){try{localStorage.setItem(KEY,JSON.stringify({world:S.world,states:S.states,transitions:S.transitions,current:S.current}));$('#save-state').textContent='Gespeichert';}catch(_){$('#save-state').textContent='Nur diese Sitzung';}}
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));if(!d?.world||!Array.isArray(d.states))return false;normalize(d);S.running=false;return true;}catch(_){return false;}}
function direction(){return [[0,-1],[1,0],[0,1],[-1,0]][S.world.dir];}
function at(list,x,y){return list.some(p=>p[0]===x&&p[1]===y);}
function renderWorld(){const w=$('#world');w.innerHTML='';for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const c=document.createElement('button');c.type='button';c.className='cell';c.dataset.x=x;c.dataset.y=y;if(at(S.world.trees,x,y)){c.classList.add('tree');c.textContent='🌳';}if(at(S.world.clovers,x,y)){c.classList.add('clover');c.textContent='☘️';}if(S.world.x===x&&S.world.y===y){const k=document.createElement('span');k.className='kara '+['north','east','south','west'][S.world.dir];k.textContent='🐞';c.append(k);}c.onclick=()=>editCell(x,y);w.append(c);}}
function editCell(x,y){if(S.selectedTool==='kara'){S.world.x=x;S.world.y=y;}else if(S.selectedTool==='turn'&&S.world.x===x&&S.world.y===y)S.world.dir=(S.world.dir+1)%4;else if(S.selectedTool==='tree'){const i=S.world.trees.findIndex(p=>p[0]===x&&p[1]===y);i<0?S.world.trees.push([x,y]):S.world.trees.splice(i,1);}else if(S.selectedTool==='clover'){const i=S.world.clovers.findIndex(p=>p[0]===x&&p[1]===y);i<0?S.world.clovers.push([x,y]):S.world.clovers.splice(i,1);}else{S.world.trees=S.world.trees.filter(p=>p[0]!==x||p[1]!==y);S.world.clovers=S.world.clovers.filter(p=>p[0]!==x||p[1]!==y);}save();renderWorld();}
function sensor(){const[dx,dy]=direction();if(at(S.world.trees,S.world.x+dx,S.world.y+dy))return sensors[1];if(at(S.world.clovers,S.world.x,S.world.y))return sensors[2];return sensors[0];}
function doAction(a){if(a===actions[0]){const[dx,dy]=direction(),nx=S.world.x+dx,ny=S.world.y+dy;if(nx<0||ny<0||nx>=SIZE||ny>=SIZE||at(S.world.trees,nx,ny))return false;S.world.x=nx;S.world.y=ny;}else if(a===actions[1])S.world.dir=(S.world.dir+3)%4;else if(a===actions[2])S.world.dir=(S.world.dir+1)%4;else if(a===actions[3]){const i=S.world.clovers.findIndex(p=>p[0]===S.world.x&&p[1]===S.world.y);if(i<0)return false;S.world.clovers.splice(i,1);S.world.collected++;}else if(a===actions[4]){if(at(S.world.clovers,S.world.x,S.world.y))return false;S.world.clovers.push([S.world.x,S.world.y]);}return true;}
function point(e){const r=$('#diagram').getBoundingClientRect();return{x:Math.max(7,Math.min(93,(e.clientX-r.left)/r.width*100)),y:Math.max(12,Math.min(88,(e.clientY-r.top)/r.height*100))};}
function pathFor(a,b){if(a.id===b.id)return `M ${a.x} ${a.y-7} C ${a.x+15} ${a.y-28}, ${a.x+25} ${a.y+8}, ${a.x+3} ${a.y+7}`;const dx=b.x-a.x,dy=b.y-a.y,curve=Math.max(8,Math.min(22,Math.abs(dx)*.18));return `M ${a.x} ${a.y} Q ${(a.x+b.x)/2} ${(a.y+b.y)/2-curve} ${b.x} ${b.y}`;}
function renderDiagram(){const d=$('#diagram'),w=d.clientWidth||700,h=d.clientHeight||470;const by=id=>S.states.find(s=>s.id===id);let svg=`<svg class="diagram-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#163047"/></marker><marker id="start-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#217653"/></marker></defs>`;S.states.forEach(s=>{if(s.start)svg+=`<path class="start-path" d="M ${s.x-14} ${s.y} L ${s.x-7} ${s.y}" marker-end="url(#start-arrow)"/>`;});S.transitions.forEach(t=>{const a=by(t.from),b=by(t.to);if(a&&b)svg+=`<path class="transition-path ${S.selectedTransition===t.id?'selected':''}" data-transition="${esc(t.id)}" d="${pathFor(a,b)}" marker-end="url(#arrow)"/><text class="transition-label ${S.selectedTransition===t.id?'selected':''}" data-transition="${esc(t.id)}" x="${a.id===b.id?a.x+15:(a.x+b.x)/2}" y="${a.id===b.id?a.y-18:(a.y+b.y)/2-5}">${esc(t.sensor)} / ${esc(t.action)}</text>`;});svg+='</svg>';d.innerHTML=svg+S.states.map(s=>`<div class="diagram-node-wrap" style="left:${s.x}%;top:${s.y}%"><button class="node ${s.id===S.current?'active':''} ${s.end?'end':''}" data-node="${esc(s.id)}" aria-label="Zustand ${esc(s.label)}">${esc(s.label)}<span class="port" data-port="${esc(s.id)}" title="Übergang zeichnen">↗</span></button></div>`).join('');d.querySelectorAll('[data-transition]').forEach(el=>el.onclick=e=>{e.stopPropagation();S.selectedTransition=el.dataset.transition;S.selectedState=null;renderEditor();renderDiagram();});d.querySelectorAll('[data-node]').forEach(n=>{n.onclick=()=>{S.selectedState=n.dataset.node;S.selectedTransition=null;renderEditor();renderDiagram();};n.ondblclick=()=>{S.selectedState=n.dataset.node;renderEditor();$('#state-name')?.focus();};n.onpointerdown=e=>startStateDrag(e,n.dataset.node);});d.querySelectorAll('[data-port]').forEach(p=>p.onpointerdown=e=>startLink(e,p.dataset.port));}
function startStateDrag(e,id){if(e.target.closest('.port'))return;e.preventDefault();S.drag={kind:'state',id};document.onpointermove=moveDrag;document.onpointerup=endDrag;}
function startLink(e,id){e.preventDefault();e.stopPropagation();S.drag={kind:'link',from:id};document.onpointermove=moveDrag;document.onpointerup=endDrag;}
function moveDrag(e){if(!S.drag)return;if(S.drag.kind==='state'){const p=point(e),s=S.states.find(x=>x.id===S.drag.id);s.x=p.x;s.y=p.y;renderDiagram();}else{$('#diagram').classList.add('linking');}}
function endDrag(e){if(!S.drag)return;const drag=S.drag;S.drag=null;document.onpointermove=null;document.onpointerup=null;$('#diagram').classList.remove('linking');if(drag.kind==='link'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]')?.dataset.node;if(target&&target!==drag.from){const t={id:uid('t',S.transitions),from:drag.from,to:target,sensor:sensors[0],action:actions[0]};S.transitions.push(t);S.selectedTransition=t.id;S.selectedState=null;save();renderAll();}}else{save();renderDiagram();}}
function select(name,values,chosen){return `<select id="${name}">${values.map(v=>`<option ${v===chosen?'selected':''}>${esc(v)}</option>`).join('')}</select>`;}
function renderEditor(){const e=$('#diagram-editor');const t=S.transitions.find(x=>x.id===S.selectedTransition);if(t){e.innerHTML=`<div class="editor-card"><b>Übergang bearbeiten</b><label>Sensor ${select('transition-sensor',sensors,t.sensor)}</label><label>Aktion ${select('transition-action',actions,t.action)}</label><button id="delete-transition" class="danger">Übergang löschen</button></div>`;$('#transition-sensor').onchange=x=>{t.sensor=x.target.value;save();renderAll();};$('#transition-action').onchange=x=>{t.action=x.target.value;save();renderAll();};$('#delete-transition').onclick=()=>{S.transitions=S.transitions.filter(x=>x!==t);S.selectedTransition=null;save();renderAll();};return;}const st=S.states.find(x=>x.id===S.selectedState);if(!st){e.innerHTML='<p class="muted">Klicke einen Zustand oder Übergang an, um ihn zu bearbeiten.</p>';return;}e.innerHTML=`<div class="editor-card"><b>Zustand bearbeiten</b><label>Beschriftung <input id="state-name" value="${esc(st.label)}" maxlength="18"></label><button id="rename-state">Umbenennen</button><button id="set-start" class="secondary">${st.start?'Start entfernen':'Als Start markieren'}</button><button id="set-end" class="secondary">${st.end?'Ziel entfernen':'Als Ziel markieren'}</button><button id="delete-state" class="danger">Zustand löschen</button></div>`;$('#rename-state').onclick=()=>{const next=$('#state-name').value.trim();if(!next)return;st.label=next;save();renderAll();};$('#set-start').onclick=()=>{S.states.forEach(x=>x.start=false);st.start=!st.start;if(st.start)S.current=st.id;save();renderAll();};$('#set-end').onclick=()=>{st.end=!st.end;save();renderAll();};$('#delete-state').onclick=()=>{if(S.states.length<=1)return;S.states=S.states.filter(x=>x!==st);S.transitions=S.transitions.filter(x=>x.from!==st.id&&x.to!==st.id);if(S.current===st.id)S.current=S.states[0].id;S.selectedState=S.current;save();renderAll();};}
function renderAll(){renderWorld();renderDiagram();$('#state-label').textContent=`Zustand: ${S.states.find(s=>s.id===S.current)?.label||S.current}`;}
function stop(msg){S.running=false;clearTimeout(S.timer);$('#run-state').textContent='Fehler';$('#feedback').textContent=msg;$('#feedback').classList.add('bad');}
function step(){const input=sensor(),t=S.transitions.find(x=>x.from===S.current&&x.sensor===input)||S.transitions.find(x=>x.from===S.current&&x.sensor===sensors[3]);if(!t){stop(`Kein Übergang für „${input}“.`);return false;}if(!doAction(t.action)){stop('Aktion nicht möglich: Baumkollision oder Kleeblatt-Aktion an falscher Stelle.');return false;}S.current=t.to;S.selectedTransition=t.id;S.selectedState=null;$('#transition-label').textContent=`${input} → ${t.action} → ${S.states.find(s=>s.id===S.current)?.label||S.current}`;$('#feedback').classList.remove('bad');$('#feedback').textContent=S.states.find(s=>s.id===S.current)?.end?'Endzustand erreicht – Simulation pausiert.':'Übergang ausgeführt.';save();renderAll();if(S.states.find(s=>s.id===S.current)?.end){S.running=false;$('#run-state').textContent='Ziel erreicht';return false;}return true;}
function run(){if(S.running)return;S.running=true;$('#run-state').textContent='Läuft';const tick=()=>{if(S.running&&step())S.timer=setTimeout(tick,600);};tick();}
function reset(){defaultMachine();save();$('#run-state').textContent='Bereit';$('#feedback').textContent='';renderAll();}
function init(){defaultMachine();$('#start-button').onclick=()=>{$('#intro').hidden=true;$('#game').hidden=false;renderAll();};$('#restore-button').onclick=()=>{if(load()){$('#intro').hidden=true;$('#game').hidden=false;renderAll();}else $('#save-state').textContent='Noch kein Speicherstand';};$('#world-tools').querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{$('#world-tools .selected').classList.remove('selected');b.classList.add('selected');S.selectedTool=b.dataset.tool;});$('#run').onclick=run;$('#pause').onclick=()=>{S.running=false;clearTimeout(S.timer);$('#run-state').textContent='Pausiert';};$('#step').onclick=()=>{S.running=false;$('#run-state').textContent='Schrittmodus';step();};$('#reset').onclick=reset;$('#check').onclick=()=>{const ok=S.states.some(s=>s.start)&&S.states.some(s=>s.end)&&S.transitions.length>0;$('#feedback').classList.toggle('bad',!ok);$('#feedback').textContent=ok?'Gut! Dein Automat hat Start, Ziel und mindestens einen Übergang.':'Noch nicht: Markiere Start/Ziel und zeichne mindestens einen Übergang.';};$('#add-state').onclick=()=>{const s={id:uid('q',S.states),label:'Zustand '+(S.states.length+1),x:20+(S.states.length*17)%65,y:22+(S.states.length*23)%60,start:false,end:false};S.states.push(s);S.selectedState=s.id;save();renderAll();};$('#clear-machine').onclick=()=>{S.transitions=[];S.states.forEach(s=>{s.start=false;s.end=false;});S.selectedTransition=null;save();renderAll();};}
init();
})();
