const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const choice=(divisor,options,answer,explanation,extra={})=>({type:'choice',divisor,options,answer,explanation,...extra});
const yesNo=(divisor,number,answer,explanation,extra={})=>({type:'yes-no',divisor,number,answer,explanation,...extra});
const digit=(divisor,template,options,answer,explanation,extra={})=>({type:'digit',divisor,template,options,answer,explanation,...extra});
const rules=[
{n:2,title:'Teilbar durch 2',text:'Die letzte Ziffer ist 0, 2, 4, 6 oder 8.',example:'248 ist durch 2 teilbar, weil 8 gerade ist.',tasks:[choice(2,['348','351','365','379'],'348','348 endet auf 8. 8 ist gerade.'),yesNo(2,'1 426',true,'1 426 endet auf 6. Deshalb ist die Zahl durch 2 teilbar.'),digit(2,'53□',['1','4','7','9'],'4','534 endet auf 4. Deshalb ist 534 durch 2 teilbar.')]},
{n:3,title:'Teilbar durch 3',text:'Die Quersumme ist durch 3 teilbar.',example:'123: 1+2+3=6. Deshalb ist 123 durch 3 teilbar.',discovery:{prompt:'Bestimme jeweils die Quersumme der Vielfachen von 3. Was fällt dir auf?',set:'V(3) = {3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, …}',result:'Die Quersummen sind auch Vielfache von 3.',rule:'Eine Zahl ist durch 3 teilbar, wenn ihre Quersumme durch 3 teilbar ist.',levels:'⭐ AH S. 8 · ⭐⭐ AH S. 9 · ⭐⭐⭐ AH S. 9',extra:'♛ Zusatzaufgabe: ⭐ AH S. 9 · ⭐⭐ AH S. 10 · ⭐⭐⭐ AH S. 10'},tasks:[choice(3,['257','258','262','274'],'258','2 + 5 + 8 = 15. 15 ist durch 3 teilbar.'),yesNo(3,'1 254',true,'1 + 2 + 5 + 4 = 12. 12 ist durch 3 teilbar.'),digit(3,'4□2',['1','2','3','5'],'3','4 + 3 + 2 = 9. 9 ist durch 3 teilbar.')]},
{n:4,title:'Teilbar durch 4',text:'Die letzten zwei Ziffern sind durch 4 teilbar.',example:'316: 16 ist durch 4 teilbar. Also ist 316 durch 4 teilbar.',tasks:[choice(4,['722','724','726','738'],'724','Die letzten zwei Ziffern sind 24. 24 ist durch 4 teilbar.'),yesNo(4,'1 316',true,'Es reicht, auf 16 zu schauen: 16 ist durch 4 teilbar.'),digit(4,'64□',['1','4','6','9'],'4','Die letzten zwei Ziffern sind 44. 44 ist durch 4 teilbar.')]},
{n:5,title:'Teilbar durch 5',text:'Die letzte Ziffer ist 0 oder 5.',example:'1 235 endet auf 5 und ist deshalb durch 5 teilbar.',tasks:[choice(5,['1 472','1 475','1 477','1 479'],'1 475','1 475 endet auf 5.'),yesNo(5,'2 340',true,'2 340 endet auf 0. Deshalb ist die Zahl durch 5 teilbar.'),digit(5,'82□',['0','2','5','8'],'5','825 endet auf 5. Die Aufgabe fragt außerdem: nicht durch 10 – deshalb passt 0 nicht.',{notDivisors:[10]})]},
{n:6,title:'Teilbar durch 6',text:'Die Zahl ist gleichzeitig durch 2 und durch 3 teilbar.',example:'42 ist gerade und 4+2=6. Deshalb ist 42 durch 6 teilbar.',tasks:[choice(6,['132','124','135','142'],'132','132 ist gerade und 1 + 3 + 2 = 6. Die Zahl ist durch 2 und 3 teilbar.'),yesNo(6,'318',true,'318 ist gerade und 3 + 1 + 8 = 12. Deshalb ist 318 durch 6 teilbar.'),digit(6,'4□2',['1','3','5','7'],'3','432 ist gerade und 4 + 3 + 2 = 9. Deshalb ist 432 durch 6 teilbar.')]},
{n:8,title:'Teilbar durch 8',text:'Die letzten drei Ziffern sind durch 8 teilbar.',example:'1 024: 024 ist durch 8 teilbar. Also ist 1 024 durch 8 teilbar.',tasks:[choice(8,['1 242','1 248','1 254','1 262'],'1 248','Die letzten drei Ziffern sind 248. 248 : 8 = 31.'),yesNo(8,'3 416',true,'Es reicht, auf 416 zu schauen: 416 : 8 = 52.'),digit(8,'12□',['0','1','3','5'],'0','120 : 8 = 15. Deshalb passt die 0.')]},
{n:9,title:'Teilbar durch 9',text:'Die Quersumme ist durch 9 teilbar.',example:'729: 7+2+9=18. Deshalb ist 729 durch 9 teilbar.',discovery:{prompt:'Bestimme jeweils die Quersumme der Vielfachen von 9. Was fällt dir auf?',set:'V(9) = {9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135, 144, 153, …}',result:'Die Quersummen sind auch Vielfache von 9.',rule:'Eine Zahl ist durch 9 teilbar, wenn ihre Quersumme durch 9 teilbar ist.',levels:'⭐ AH S. 8 · ⭐⭐ AH S. 9 · ⭐⭐⭐ AH S. 9',extra:'♛ Zusatzaufgabe: ⭐ AH S. 9 · ⭐⭐ AH S. 10 · ⭐⭐⭐ AH S. 10'},tasks:[choice(9,['638','639','641','650'],'639','6 + 3 + 9 = 18. 18 ist durch 9 teilbar.'),yesNo(9,'4 536',true,'4 + 5 + 3 + 6 = 18. 18 ist durch 9 teilbar.'),digit(9,'7□4',['2','5','7','8'],'7','7 + 7 + 4 = 18. 18 ist durch 9 teilbar.')]},
{n:10,title:'Teilbar durch 10',text:'Die letzte Ziffer ist 0.',example:'5 430 endet auf 0 und ist deshalb durch 10 teilbar.',tasks:[choice(10,['3 210','3 212','3 215','3 218'],'3 210','3 210 endet auf 0.'),yesNo(10,'7 890',true,'7 890 endet auf 0. Deshalb ist die Zahl durch 10 teilbar.'),digit(10,'46□',['0','2','5','8'],'0','460 endet auf 0. Deshalb ist 460 durch 10 teilbar.')]}
];
const practiceTasks=rules.flatMap(rule=>rule.tasks.map((task,index)=>({...task,rule:rule.n,label:`Regel ${rule.n} · Aufgabe ${index+1}`})));
const masterTasks=[
choice(6,['234','236','243','248'],'234','234 ist gerade und 2 + 3 + 4 = 9. Deshalb ist 234 durch 6 teilbar.',{label:'Kombination · durch 2 und 3'}),
yesNo(8,'1 728',true,'Es reicht, auf 728 zu schauen: 728 : 8 = 91.',{label:'Kombination · genau hinschauen'}),
digit(3,'6□3',['1','3','5','8'],'3','6 + 3 + 3 = 12. 12 ist durch 3, aber nicht durch 9 teilbar.',{notDivisors:[9],label:'Kombination · durch 3, nicht durch 9'}),
choice(4,['340','342','350','370'],'340','340 endet auf 0 und die letzten zwei Ziffern 40 sind durch 4 teilbar. Also ist 340 durch 4 und 5 teilbar.',{divisors:[4,5],label:'Kombination · durch 4 und 5'}),
yesNo(6,'4 590',true,'4 590 ist gerade und 4 + 5 + 9 + 0 = 18. Deshalb ist die Zahl durch 6 teilbar.',{label:'Kombination · durch 2 und 3'}),
digit(8,'72□',['0','1','3','5'],'0','720 : 8 = 90. Deshalb passt die 0.',{label:'Knobelaufgabe · durch 8'}),
choice(9,['729','735','741','753'],'729','7 + 2 + 9 = 18. 18 ist durch 9 und damit auch durch 3 teilbar.',{divisors:[3,9],label:'Kombination · durch 3 und 9'}),
yesNo(5,'1 125',true,'1 125 endet auf 5. Deshalb ist die Zahl durch 5, aber nicht durch 10 teilbar.',{notDivisors:[10],label:'Kombination · durch 5, nicht durch 10'}),
digit(6,'9□6',['1','3','5','8'],'3','936 ist gerade und 9 + 3 + 6 = 18. Deshalb ist 936 durch 6 teilbar.',{label:'Kombination · durch 2 und 3'}),
yesNo(4,'2 304',true,'Es reicht, auf 04 zu schauen: 4 ist durch 4 teilbar.',{label:'Genau hinschauen · durch 4'}),
choice(8,['1 024','1 022','1 026','1 030'],'1 024','Die letzten drei Ziffern sind 024. 24 ist durch 8 teilbar.',{notDivisors:[3],label:'Kombination · durch 8, nicht durch 3'}),
digit(5,'4□',['0','2','5','8'],'5','45 endet auf 5. Deshalb ist die Zahl durch 5, aber nicht durch 10 teilbar.',{notDivisors:[10],label:'Knobelaufgabe · durch 5, nicht durch 10'})
];
function toNumber(value){return Number(String(value).replace(/\D/g,''))}
function targetDivisors(task){return task.divisors||[task.divisor]}
function matches(value,task){const number=toNumber(value);return targetDivisors(task).every(divisor=>number%divisor===0)&&(task.notDivisors||[]).every(divisor=>number%divisor!==0)}
function candidateValue(task,candidate){return task.type==='digit'?task.template.replace('□',candidate):candidate}
function validateTaskBank(){[...practiceTasks,...masterTasks].forEach((task,index)=>{const values=task.type==='yes-no'?[task.number]:task.options;if(!values.length||new Set(values).size!==values.length)throw new Error(`Ungültige Antwortoptionen in Aufgabe ${index+1}.`);if(!targetDivisors(task).every(Number.isInteger)||!(task.notDivisors||[]).every(Number.isInteger))throw new Error(`Ungültiger Teiler in Aufgabe ${index+1}.`);if(task.type==='yes-no'){if(matches(task.number,task)!==task.answer)throw new Error(`Falsche Ja/Nein-Lösung in Aufgabe ${index+1}.`);return}const correct=values.filter(value=>matches(candidateValue(task,value),task));if(correct.length!==1||String(correct[0])!==String(task.answer))throw new Error(`Falsche Lösung in Aufgabe ${index+1}.`)});}
validateTaskBank();
const state={mode:'learn',index:0,score:0,correct:0,sound:true,answered:false,items:[]};
function show(id){$$('.screen').forEach(x=>{x.hidden=x.id!==id;x.classList.toggle('active',x.id===id)});window.scrollTo({top:0,behavior:'smooth'})}
function beep(ok){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.value=.05;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}
function save(){localStorage.setItem('linguacode-teilbarkeit-score',String(Math.max(Number(localStorage.getItem('linguacode-teilbarkeit-score')||0),state.score)))}
function optionsMarkup(options){return `<div class="options">${options.map(option=>`<button class="option" type="button" data-answer="${option}">${option}</button>`).join('')}</div>`}
function renderTask(task){const label=task.label?`<p class="task-label">${task.label}</p>`:'';const divisors=targetDivisors(task).join(' und ');const excluded=task.notDivisors?.length?` und nicht durch ${task.notDivisors.join(' und ')}`:'';if(task.type==='choice')return `${label}<p class="explanation">Welche Zahl ist durch <strong>${divisors}</strong>${excluded} teilbar?</p>${optionsMarkup(task.options)}`;if(task.type==='yes-no')return `${label}<p class="explanation">Ist <strong>${task.number}</strong> durch <strong>${divisors}</strong>${excluded} teilbar?</p>${optionsMarkup(['Ja','Nein'])}`;return `${label}<p class="explanation">Welche Ziffer passt in <strong>${task.template}</strong>, damit die Zahl durch <strong>${divisors}</strong>${excluded} teilbar ist?</p>${optionsMarkup(task.options)}`}
function render(){const item=state.items[state.index];state.answered=false;const learn=state.mode==='learn';$('#counter').textContent=`${learn?'Karte':'Aufgabe'} ${state.index+1} von ${state.items.length}`;$('#score').textContent=`${state.score} Punkte`;$('#progress-bar').style.width=`${state.index/state.items.length*100}%`;$('#feedback').className='feedback';$('#feedback').textContent='';$('#hint-button').textContent=learn?'💡 Merksatz':'💡 Tipp';if(learn){const body=`<p class="explanation">${item.text}</p><div class="example">${item.example}</div>${item.discovery?`<div class="discovery"><strong>Entdecke:</strong> ${item.discovery.prompt}<p>${item.discovery.set}</p><b>${item.discovery.result}</b><p class="rule-callout">${item.discovery.rule}</p><small>${item.discovery.levels}<br>${item.discovery.extra}</small></div>`:''}`;$('#card').innerHTML=`<div class="rule-number">${item.n}</div><h2>${item.title}</h2>${body}`}else{$('#card').innerHTML=`<div class="rule-number">${item.rule||'★'}</div><h2>${state.mode==='master'?'Meisterfrage':'Zahlen-Detektei'}</h2>${renderTask(item)}`;$$('.option').forEach(button=>button.addEventListener('click',()=>answer(button,item)))}}
function answer(button,task){if(state.answered)return;state.answered=true;const selected=task.type==='yes-no'?button.dataset.answer==='Ja':button.dataset.answer;const ok=String(selected)===String(task.answer);$$('.option').forEach(option=>option.disabled=true);button.classList.add(ok?'correct':'wrong');if(ok){state.correct++;state.score+=10;$('#feedback').className='feedback show good';$('#feedback').textContent=`✅ Richtig! ${task.explanation}`;beep(true)}else{$('#feedback').className='feedback show';$('#feedback').textContent=`Noch nicht. ${task.explanation}`;beep(false)}$('#score').textContent=`${state.score} Punkte`;save()}
function next(){if(state.index>=state.items.length-1){finish();return}state.index++;render()}
function finish(){$('#finish-score').textContent=state.score;$('#finish-correct').textContent=`${state.correct}/${state.items.length}`;$('#finish-message').textContent=state.correct===state.items.length?'Du beherrschst die Teilbarkeitsregeln sicher.':'Guter Start – wiederhole die Regeln mit „Entdecken“ und versuche es noch einmal.';show('finish-screen')}
function startMode(){state.index=0;state.score=0;state.correct=0;state.items=state.mode==='learn'?rules:state.mode==='practice'?practiceTasks:masterTasks;$('#mode-label').textContent=state.mode==='learn'?'ENTDECKEN':state.mode==='practice'?'TRAINIEREN':'MEISTERPRÜFUNG';$('#activity-title').textContent=state.mode==='learn'?'Regelkarte':state.mode==='practice'?'Zahlen-Detektei':'Meisterprüfung';show('activity-screen');render()}
$$('.mode-card').forEach(button=>button.addEventListener('click',()=>{$$('.mode-card').forEach(card=>card.classList.remove('selected'));button.classList.add('selected');state.mode=button.dataset.mode}));$('#start-button').addEventListener('click',startMode);$('#next-button').addEventListener('click',next);$('#hint-button').addEventListener('click',()=>{const item=state.items[state.index];$('#feedback').className='feedback show';$('#feedback').textContent=state.mode==='learn'?`Merksatz: ${item.text}`:`Tipp: ${item.explanation}`});$('#back-button').addEventListener('click',()=>show('start-screen'));$('#home-button').addEventListener('click',()=>show('start-screen'));$('#again-button').addEventListener('click',startMode);$('#sound-toggle').addEventListener('click',event=>{state.sound=!state.sound;event.currentTarget.textContent=state.sound?'🔊 Ton':'🔇 Ton';event.currentTarget.setAttribute('aria-pressed',state.sound)});
