const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const rules=[
  {n:2,title:'Teilbar durch 2',text:'Die letzte Ziffer ist 0, 2, 4, 6 oder 8.',example:'248 ist durch 2 teilbar, weil 8 gerade ist.',options:['248','235','417','591'],answer:'248'},
  {n:3,title:'Teilbar durch 3',text:'Die Quersumme ist durch 3 teilbar.',example:'123: 1+2+3=6. Deshalb ist 123 durch 3 teilbar.',options:['124','123','125','127'],answer:'123'},
  {n:4,title:'Teilbar durch 4',text:'Die letzten zwei Ziffern sind durch 4 teilbar.',example:'316: 16 ist durch 4 teilbar. Also ist 316 durch 4 teilbar.',options:['318','326','316','342'],answer:'316'},
  {n:5,title:'Teilbar durch 5',text:'Die letzte Ziffer ist 0 oder 5.',example:'1 235 endet auf 5 und ist deshalb durch 5 teilbar.',options:['1 234','1 235','1 237','1 239'],answer:'1 235'},
  {n:6,title:'Teilbar durch 6',text:'Die Zahl ist gleichzeitig durch 2 und durch 3 teilbar.',example:'42 ist gerade und 4+2=6. Deshalb ist 42 durch 6 teilbar.',options:['35','41','42','49'],answer:'42'},
  {n:8,title:'Teilbar durch 8',text:'Die letzten drei Ziffern sind durch 8 teilbar.',example:'1 024: 024 ist durch 8 teilbar. Also ist 1 024 durch 8 teilbar.',options:['1 022','1 024','1 026','1 028'],answer:'1 024'},
  {n:9,title:'Teilbar durch 9',text:'Die Quersumme ist durch 9 teilbar.',example:'729: 7+2+9=18. Deshalb ist 729 durch 9 teilbar.',options:['728','729','730','731'],answer:'729'},
  {n:10,title:'Teilbar durch 10',text:'Die letzte Ziffer ist 0.',example:'5 430 endet auf 0 und ist deshalb durch 10 teilbar.',options:['5 431','5 432','5 435','5 430'],answer:'5 430'}
];
const state={mode:'learn',index:0,score:0,correct:0,sound:true,answered:false};
function show(id){$$('.screen').forEach(x=>{x.hidden=x.id!==id;x.classList.toggle('active',x.id===id)});window.scrollTo({top:0,behavior:'smooth'})}
function beep(ok){if(!state.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?660:180;g.gain.value=.05;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}
function save(){localStorage.setItem('linguacode-teilbarkeit-score',String(Math.max(Number(localStorage.getItem('linguacode-teilbarkeit-score')||0),state.score)))}
function render(){const r=rules[state.index];state.answered=false;$('#counter').textContent=`${state.mode==='learn'?'Karte':'Aufgabe'} ${state.index+1} von ${rules.length}`;$('#score').textContent=`${state.score} Punkte`;$('#progress-bar').style.width=`${state.index/rules.length*100}%`;$('#feedback').className='feedback';$('#feedback').textContent='';$('#hint-button').textContent=state.mode==='learn'?'💡 Merksatz':'💡 Tipp';let body='';if(state.mode==='learn'){body=`<p class="explanation">${r.text}</p><div class="example">${r.example}</div>`}else{body=`<p class="explanation">Welche Zahl ist durch <strong>${r.n}</strong> teilbar?</p><div class="options">${r.options.map(o=>`<button class="option" type="button" data-answer="${o}">${o}</button>`).join('')}</div>`}$('#card').innerHTML=`<div class="rule-number">${r.n}</div><h2>${r.title}</h2>${body}`;$$('.option').forEach(b=>b.addEventListener('click',()=>answer(b)))}
function answer(button){if(state.answered)return;state.answered=true;const r=rules[state.index],ok=button.dataset.answer===r.answer;button.classList.add(ok?'correct':'wrong');if(ok){state.correct++;state.score+=10;$('#feedback').className='feedback show good';$('#feedback').textContent='✅ Richtig! '+r.text;beep(true)}else{$('#feedback').className='feedback show';$('#feedback').textContent=`Noch nicht. Die richtige Zahl ist ${r.answer}. ${r.example}`;beep(false)}$('#score').textContent=`${state.score} Punkte`;save()}
function next(){if(state.index>=rules.length-1){finish();return}state.index++;render()}
function finish(){$('#finish-score').textContent=state.score;$('#finish-correct').textContent=`${state.correct}/${rules.length}`;$('#finish-message').textContent=state.correct===rules.length?'Du beherrschst die Regeln sicher.':'Guter Start – wiederhole die Regeln mit „Entdecken“ und versuche es noch einmal.';show('finish-screen')}
$$('.mode-card').forEach(b=>b.addEventListener('click',()=>{$$('.mode-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode}));$('#start-button').addEventListener('click',()=>{state.index=0;state.score=0;state.correct=0;$('#mode-label').textContent=state.mode==='learn'?'ENTDECKEN':state.mode==='practice'?'TRAINIEREN':'MEISTERPRÜFUNG';$('#activity-title').textContent=state.mode==='learn'?'Regelkarte':'Zahlen-Detektei';show('activity-screen');render()});$('#next-button').addEventListener('click',next);$('#hint-button').addEventListener('click',()=>{const r=rules[state.index];$('#feedback').className='feedback show';$('#feedback').textContent=state.mode==='learn'?`Merksatz: ${r.text}`:`Denke an die Regel für ${r.n}. Beispiel: ${r.example}`});$('#back-button').addEventListener('click',()=>show('start-screen'));$('#home-button').addEventListener('click',()=>show('start-screen'));$('#again-button').addEventListener('click',()=>{$('#start-button').click()});$('#sound-toggle').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'🔊 Ton':'🔇 Ton';e.currentTarget.setAttribute('aria-pressed',state.sound)});
